// Single-member tuning rig. The agent (you, reading this) plays the partner
// in free-form text. The focus member is generated by the live AI prompt
// pipeline. This service is the thin layer that turns a serializable
// "tune session" (transcript + identities) into a real CharacterPromptPacket
// and AI call, using the exact same date-prompts machinery as gameplay.

import {
  dateMessageSchema,
  dateSessionSchema,
  judgeSnapshotSchema,
  type CupidIntervention,
  type DateMessage,
  type DateScenario,
  type DateSession,
  type JudgeSnapshot,
  type Member,
  type PairState,
} from "../domain/game";
import { starterMembers, starterScenarios } from "../fixtures";
import type { MemoryPack } from "./cupid-memory";
import {
  buildCharacterPromptPacket,
  hasNearDuplicateRecentLine,
  hasRepeatedApprovalPhrase,
  withCharacterVisibilityRetryGuard,
  type CharacterPromptPacket,
} from "./date-prompts";
import { EmptyPerformerMessageError, sanitizeCharacterText } from "./ai-date-engine";
import {
  generateCharacterTurn,
  type AiRuntimeConfig,
  type GeneratedTextResult,
} from "./ai/model-service";
import { requirePairState } from "./date-engine";
import { createSeedGameSave } from "./game-seed";
import {
  ensureScenarioInDeck,
  startAndDraftDateSession,
  withFeaturedMembers,
} from "./test-helpers";

export const TUNE_SCHEMA_VERSION = 1 as const;
export const DEFAULT_TUNE_SCENARIO_ID = "diner-eleven-pm";
export const DEFAULT_TUNE_PARTNER_ID = "alex-yoon";

const EMPTY_MEMORY_PACK: MemoryPack = {
  self: [],
  pair: [],
  scenario: [],
  recentTranscript: [],
};

export type TuneTranscriptMessage =
  | {
      kind: "character";
      speakerId: string;
      text: string;
      createdAt: string;
    }
  | {
      kind: "scenario";
      text: string;
      createdAt: string;
    }
  | {
      kind: "cupid";
      text: string;
      targetMemberId: string;
      createdAt: string;
    }
  | {
      kind: "judge";
      dateHealthDelta: number;
      note: string;
      createdAt: string;
    };

export type TuneSessionPersisted = {
  schemaVersion: typeof TUNE_SCHEMA_VERSION;
  createdAt: string;
  focusMemberId: string;
  partnerMemberId: string;
  scenarioId: string;
  openerSide: "partner" | "focus";
  messages: TuneTranscriptMessage[];
  lastPromptSystem?: string;
  notes?: string;
};

export type TuneSessionInput = {
  focusMemberId: string;
  partnerMemberId?: string;
  scenarioId?: string;
  openerSide?: "partner" | "focus";
  now?: Date;
};

export function listAvailableMembers(): readonly Member[] {
  return starterMembers;
}

export function listAvailableScenarios(): readonly DateScenario[] {
  return starterScenarios;
}

export function findMemberById(memberId: string): Member | undefined {
  return starterMembers.find((member) => member.id === memberId);
}

export function findScenarioById(scenarioId: string): DateScenario | undefined {
  return starterScenarios.find((scenario) => scenario.id === scenarioId);
}

function requireMemberForTune(memberId: string, role: "focus" | "partner"): Member {
  const member = findMemberById(memberId);
  if (member === undefined) {
    throw new Error(`Unknown ${role} member id: ${memberId}`);
  }
  return member;
}

function requireScenarioForTune(scenarioId: string): DateScenario {
  const scenario = findScenarioById(scenarioId);
  if (scenario === undefined) {
    throw new Error(`Unknown scenario id: ${scenarioId}`);
  }
  return scenario;
}

export function createTuneSession(input: TuneSessionInput): TuneSessionPersisted {
  const focusMember = requireMemberForTune(input.focusMemberId, "focus");
  const partnerMemberId = input.partnerMemberId ?? DEFAULT_TUNE_PARTNER_ID;
  if (partnerMemberId === input.focusMemberId) {
    throw new Error("Partner and focus member cannot be the same.");
  }
  const partnerMember = requireMemberForTune(partnerMemberId, "partner");
  const scenarioId = input.scenarioId ?? DEFAULT_TUNE_SCENARIO_ID;
  requireScenarioForTune(scenarioId);
  const openerSide = input.openerSide ?? "partner";
  const createdAt = (input.now ?? new Date()).toISOString();

  return {
    schemaVersion: TUNE_SCHEMA_VERSION,
    createdAt,
    focusMemberId: focusMember.id,
    partnerMemberId: partnerMember.id,
    scenarioId,
    openerSide,
    messages: [],
  };
}

export function appendPartnerLine(
  session: TuneSessionPersisted,
  text: string,
  now: Date = new Date(),
): TuneSessionPersisted {
  const trimmed = text.trim();
  if (trimmed.length === 0) {
    throw new Error("Partner line cannot be empty.");
  }
  assertCanAppendCharacterLine(session, session.partnerMemberId);
  return {
    ...session,
    messages: [
      ...session.messages,
      {
        kind: "character",
        speakerId: session.partnerMemberId,
        text: trimmed,
        createdAt: now.toISOString(),
      },
    ],
  };
}

export function appendDirectorEvent(
  session: TuneSessionPersisted,
  text: string,
  now: Date = new Date(),
): TuneSessionPersisted {
  const trimmed = text.trim();
  if (trimmed.length === 0) {
    throw new Error("Director event text cannot be empty.");
  }
  return {
    ...session,
    messages: [
      ...session.messages,
      {
        kind: "scenario",
        text: trimmed,
        createdAt: now.toISOString(),
      },
    ],
  };
}

export function appendJudgeSnapshot(
  session: TuneSessionPersisted,
  input: { dateHealthDelta: number; note?: string },
  now: Date = new Date(),
): TuneSessionPersisted {
  const delta = Math.round(input.dateHealthDelta);
  if (!Number.isFinite(delta)) {
    throw new Error("Judge dateHealthDelta must be a finite number.");
  }
  if (delta < -50 || delta > 50) {
    throw new Error("Judge dateHealthDelta must be between -50 and 50.");
  }
  const note = (input.note ?? "Manual judge snapshot.").trim();
  if (note.length === 0) {
    throw new Error("Judge note cannot be empty.");
  }
  return {
    ...session,
    messages: [
      ...session.messages,
      {
        kind: "judge",
        dateHealthDelta: delta,
        note,
        createdAt: now.toISOString(),
      },
    ],
  };
}

export function appendCupidNote(
  session: TuneSessionPersisted,
  text: string,
  now: Date = new Date(),
): TuneSessionPersisted {
  const trimmed = text.trim();
  if (trimmed.length === 0) {
    throw new Error("Cupid note text cannot be empty.");
  }
  const CUPID_NOTE_MAX_LENGTH = 240;
  if (trimmed.length > CUPID_NOTE_MAX_LENGTH) {
    throw new Error(
      `Cupid note must be ${CUPID_NOTE_MAX_LENGTH} characters or fewer. Got ${trimmed.length}.`,
    );
  }
  return {
    ...session,
    messages: [
      ...session.messages,
      {
        kind: "cupid",
        text: trimmed,
        targetMemberId: session.focusMemberId,
        createdAt: now.toISOString(),
      },
    ],
  };
}

function appendFocusMemberReply(
  session: TuneSessionPersisted,
  text: string,
  systemPrompt: string,
  now: Date = new Date(),
): TuneSessionPersisted {
  assertCanAppendCharacterLine(session, session.focusMemberId);
  return {
    ...session,
    lastPromptSystem: systemPrompt,
    messages: [
      ...session.messages,
      {
        kind: "character",
        speakerId: session.focusMemberId,
        text,
        createdAt: now.toISOString(),
      },
    ],
  };
}

function assertCanAppendCharacterLine(session: TuneSessionPersisted, speakerId: string): void {
  const lastCharacter = findLastCharacterMessage(session);

  if (lastCharacter?.speakerId === speakerId) {
    const command =
      speakerId === session.focusMemberId
        ? "`tune retry` to replace the last focus reply or `tune say` to answer it"
        : "`tune turn` to generate the focus member's reply";
    throw new Error(`Cannot append two consecutive turns for ${speakerId}. Use ${command}.`);
  }
}

function findLastCharacterMessage(
  session: TuneSessionPersisted,
): Extract<TuneTranscriptMessage, { kind: "character" }> | undefined {
  for (let index = session.messages.length - 1; index >= 0; index -= 1) {
    const message = session.messages[index];

    if (message?.kind === "character") {
      return message;
    }
  }

  return undefined;
}

export function dropLastFocusMemberReply(session: TuneSessionPersisted): TuneSessionPersisted {
  const lastMessage = session.messages[session.messages.length - 1];

  if (
    lastMessage === undefined ||
    lastMessage.kind !== "character" ||
    lastMessage.speakerId !== session.focusMemberId
  ) {
    throw new Error("Last tune message is not a focus member reply. Run `tune turn` first.");
  }

  return {
    ...session,
    lastPromptSystem: undefined,
    messages: session.messages.slice(0, -1),
  };
}

type ReconstructedContext = {
  focusMember: Member;
  partnerMember: Member;
  scenario: DateScenario;
  pairState: PairState;
  dateSession: DateSession;
};

function reconstructContext(session: TuneSessionPersisted): ReconstructedContext {
  const focusMember = requireMemberForTune(session.focusMemberId, "focus");
  const partnerMember = requireMemberForTune(session.partnerMemberId, "partner");
  const scenario = requireScenarioForTune(session.scenarioId);

  const seedSave = createSeedGameSave(new Date(session.createdAt));
  const featured = withFeaturedMembers(seedSave, [focusMember.id, partnerMember.id]);
  const saveWithScenario = ensureScenarioInDeck(featured, scenario.id);
  const firstMemberId = session.openerSide === "focus" ? focusMember.id : partnerMember.id;
  const secondMemberId = session.openerSide === "focus" ? partnerMember.id : focusMember.id;

  const started = startAndDraftDateSession(saveWithScenario, {
    focusMemberId: focusMember.id,
    firstMemberId,
    secondMemberId,
    scenarioId: scenario.id,
    now: new Date(session.createdAt),
  });

  const baseSession = started.session;
  const pairState = requirePairState(started.save, baseSession.pairId);

  const reconstructed = reconstructTranscriptAndInterventions(session, baseSession);

  const dateSession = dateSessionSchema.parse({
    ...baseSession,
    transcript: reconstructed.transcript,
    interventions: reconstructed.interventions,
    judgeSnapshots: reconstructed.judgeSnapshots,
    dateHealth: reconstructed.dateHealth,
    currentTurn: reconstructed.currentTurn,
    playbackState: "playing",
  });

  return {
    focusMember,
    partnerMember,
    scenario,
    pairState,
    dateSession,
  };
}

function reconstructTranscriptAndInterventions(
  session: TuneSessionPersisted,
  baseSession: DateSession,
): {
  transcript: DateMessage[];
  interventions: CupidIntervention[];
  judgeSnapshots: JudgeSnapshot[];
  dateHealth: number;
  currentTurn: number;
} {
  const transcript: DateMessage[] = [...baseSession.transcript];
  const interventions: CupidIntervention[] = [];
  const judgeSnapshots: JudgeSnapshot[] = [...baseSession.judgeSnapshots];
  let dateHealth = baseSession.dateHealth;
  let characterCount = 0;
  let sequenceIndex = transcript.length;
  let judgeCount = 0;

  for (const message of session.messages) {
    const currentTurnIndex = characterCount;
    const nextCharacterTurnIndex = characterCount + 1;
    const baseId = `tune-${baseSession.id}-msg-${sequenceIndex}`;
    if (message.kind === "character") {
      transcript.push(
        dateMessageSchema.parse({
          kind: "character",
          id: baseId,
          dateSessionId: baseSession.id,
          turnIndex: nextCharacterTurnIndex,
          sequenceIndex,
          text: message.text,
          createdAt: message.createdAt,
          speakerId: message.speakerId,
        }),
      );
      characterCount += 1;
    } else if (message.kind === "scenario") {
      transcript.push(
        dateMessageSchema.parse({
          kind: "scenario",
          id: baseId,
          dateSessionId: baseSession.id,
          turnIndex: currentTurnIndex,
          sequenceIndex,
          text: message.text,
          createdAt: message.createdAt,
        }),
      );
    } else if (message.kind === "cupid") {
      transcript.push(
        dateMessageSchema.parse({
          kind: "cupid",
          id: baseId,
          dateSessionId: baseSession.id,
          turnIndex: currentTurnIndex,
          sequenceIndex,
          text: message.text,
          createdAt: message.createdAt,
          targetMemberId: message.targetMemberId,
        }),
      );
      interventions.push({
        id: `tune-cupid-${sequenceIndex}`,
        text: message.text,
        usedAtTurn: currentTurnIndex,
        targetMemberId: message.targetMemberId,
      });
    } else {
      judgeCount += 1;
      const memberMoodDeltas: Record<string, number> = {
        [session.focusMemberId]: 0,
        [session.partnerMemberId]: 0,
      };
      judgeSnapshots.push(
        judgeSnapshotSchema.parse({
          id: `tune-${baseSession.id}-judge-${judgeCount}`,
          dateSessionId: baseSession.id,
          exchangeIndex: Math.max(characterCount, 1),
          dateHealthDelta: message.dateHealthDelta,
          statDeltas: {},
          memberMoodDeltas,
          shouldEndEarly: false,
          endSentiment: null,
          notableMoments: [message.note],
          playerSummary: message.note,
          memoryCandidates: [],
        }),
      );
      dateHealth = clampDateHealth(dateHealth + message.dateHealthDelta);
    }
    sequenceIndex += 1;
  }

  return {
    transcript,
    interventions,
    judgeSnapshots,
    dateHealth,
    currentTurn: characterCount,
  };
}

function clampDateHealth(value: number): number {
  if (value < 0) return 0;
  if (value > 100) return 100;
  return Math.round(value);
}

export type TunePacketPreview = {
  packet: CharacterPromptPacket;
  focusMember: Member;
  partnerMember: Member;
  scenario: DateScenario;
  pairState: PairState;
  dateSession: DateSession;
};

export function previewMemberTurnPacket(session: TuneSessionPersisted): TunePacketPreview {
  const context = reconstructContext(session);
  const packet = buildCharacterPromptPacket({
    member: context.focusMember,
    partner: context.partnerMember,
    scenario: context.scenario,
    session: context.dateSession,
    pairState: context.pairState,
    memoryPack: { ...EMPTY_MEMORY_PACK, recentTranscript: context.dateSession.transcript },
  });
  return { ...context, packet };
}

export type TuneGenerationResult = {
  session: TuneSessionPersisted;
  replyText: string;
  rawText: string;
  preview: TunePacketPreview;
  retried: boolean;
  retryReason: "near_duplicate" | "approval_phrase" | "visibility" | null;
  warningMessages: string[];
  promptCharacters: number;
  approximatePromptTokens: number;
  modelId: string;
  providerMode: string;
};

export type GenerateOptions = {
  config?: Partial<AiRuntimeConfig>;
  now?: Date;
};

export async function generateFocusMemberReply(
  session: TuneSessionPersisted,
  options: GenerateOptions = {},
): Promise<TuneGenerationResult> {
  assertCanAppendCharacterLine(session, session.focusMemberId);
  const preview = previewMemberTurnPacket(session);
  const warningMessages: string[] = [];
  const recentSpeakerLines = collectRecentFocusLines(preview.dateSession, preview.focusMember.id);

  const config = options.config ?? {};
  const runVisibleAttempt = async (
    packet: CharacterPromptPacket,
  ): Promise<{
    attempt: { text: string; raw: GeneratedTextResult };
    retriedForVisibility: boolean;
  }> => {
    try {
      const attempt = await runOnce({
        packet,
        config,
        speakerName: preview.focusMember.name,
      });
      return { attempt, retriedForVisibility: false };
    } catch (error) {
      if (!(error instanceof EmptyPerformerMessageError)) {
        throw error;
      }

      warningMessages.push(
        `${preview.focusMember.name} returned an empty line; retried with visibility guard.`,
      );
      const retry = await runOnce({
        packet: withCharacterVisibilityRetryGuard(packet),
        config,
        speakerName: preview.focusMember.name,
      });
      return { attempt: retry, retriedForVisibility: true };
    }
  };

  const firstVisibleAttempt = await runVisibleAttempt(preview.packet);
  const firstAttempt = firstVisibleAttempt.attempt;
  let chosen = firstAttempt;
  let retried = firstVisibleAttempt.retriedForVisibility;
  let retryReason: TuneGenerationResult["retryReason"] = firstVisibleAttempt.retriedForVisibility
    ? "visibility"
    : null;

  const initialNearDup = hasNearDuplicateRecentLine({
    text: firstAttempt.text,
    recentLines: recentSpeakerLines,
  });
  if (initialNearDup !== null) {
    warningMessages.push(`Near-duplicate detected; asked ${preview.focusMember.name} to rewrite.`);
    const retryPacket = buildRetryPacket(preview.packet, {
      repetitionRetry: initialNearDup,
    });
    const retry = await runVisibleAttempt(retryPacket);
    chosen = retry.attempt;
    retried = true;
    retryReason = retry.retriedForVisibility ? "visibility" : "near_duplicate";
  } else {
    const repeatedApproval = hasRepeatedApprovalPhrase({
      text: firstAttempt.text,
      recentLines: recentSpeakerLines,
    });
    if (repeatedApproval !== null) {
      warningMessages.push(
        `Repeated approval phrase detected; asked ${preview.focusMember.name} to rewrite.`,
      );
      const retryPacket = buildRetryPacket(preview.packet, {
        rhythmRetry: repeatedApproval,
      });
      const retry = await runVisibleAttempt(retryPacket);
      chosen = retry.attempt;
      retried = true;
      retryReason = retry.retriedForVisibility ? "visibility" : "approval_phrase";
    }
  }

  const updatedSession = appendFocusMemberReply(
    session,
    chosen.text,
    preview.packet.system,
    options.now,
  );

  return {
    session: updatedSession,
    replyText: chosen.text,
    rawText: chosen.raw.text,
    preview,
    retried,
    retryReason,
    warningMessages: [...warningMessages, ...(chosen.raw.warningMessages ?? [])],
    promptCharacters: preview.packet.prompt.length + preview.packet.system.length,
    approximatePromptTokens: Math.ceil(
      (preview.packet.prompt.length + preview.packet.system.length) / 4,
    ),
    modelId: chosen.raw.model,
    providerMode: chosen.raw.providerMode,
  };
}

function buildRetryPacket(
  basePacket: CharacterPromptPacket,
  guards:
    | { repetitionRetry: { repeatedLine: string } }
    | { rhythmRetry: { repeatedPhrase: string; recentLine: string } },
): CharacterPromptPacket {
  if ("repetitionRetry" in guards) {
    const notice = [
      "",
      `Your previous attempt repeated a recent line: "${truncate(guards.repetitionRetry.repeatedLine)}".`,
      "Rewrite. Different shape, different opener, different angle.",
    ].join("\n");
    return {
      ...basePacket,
      system: basePacket.system + notice,
      prompt: basePacket.prompt + notice,
    };
  }
  const notice = [
    "",
    `Your previous attempt reused the approval phrase "${guards.rhythmRetry.repeatedPhrase}" near "${truncate(guards.rhythmRetry.recentLine)}".`,
    "Rewrite without that opener.",
  ].join("\n");
  return {
    ...basePacket,
    system: basePacket.system + notice,
    prompt: basePacket.prompt + notice,
  };
}

function truncate(text: string, max = 80): string {
  const collapsed = text.replace(/\s+/g, " ").trim();
  return collapsed.length <= max ? collapsed : `${collapsed.slice(0, max - 1)}…`;
}

async function runOnce({
  packet,
  config,
  speakerName,
}: {
  packet: CharacterPromptPacket;
  config: Partial<AiRuntimeConfig>;
  speakerName: string;
}): Promise<{ text: string; raw: GeneratedTextResult }> {
  const raw = await generateCharacterTurn({ packet, config });
  const text = sanitizeCharacterText(raw.text, speakerName);
  return { text, raw };
}

function collectRecentFocusLines(session: DateSession, focusMemberId: string): string[] {
  const lines: string[] = [];
  for (const message of session.transcript) {
    if (message.kind === "character" && message.speakerId === focusMemberId) {
      lines.push(message.text);
    }
  }
  return lines.slice(-3);
}

export function formatTranscriptForReading(
  session: TuneSessionPersisted,
  context: { focusName: string; partnerName: string },
): string {
  if (session.messages.length === 0) {
    return "(no messages yet)";
  }
  const lines: string[] = [];
  for (const message of session.messages) {
    if (message.kind === "character") {
      const label =
        message.speakerId === session.focusMemberId
          ? `${context.focusName} (focus)`
          : `${context.partnerName} (you)`;
      lines.push(`${label}: ${message.text}`);
    } else if (message.kind === "scenario") {
      lines.push(`[event] ${message.text}`);
    } else if (message.kind === "cupid") {
      lines.push(`[cupid to ${context.focusName}] ${message.text}`);
    } else {
      const sign =
        message.dateHealthDelta >= 0 ? `+${message.dateHealthDelta}` : `${message.dateHealthDelta}`;
      lines.push(`[judge ${sign} health] ${message.note}`);
    }
  }
  return lines.join("\n");
}
