export type StandeeFooting = {
  topTransparentPixels: number;
  bottomTransparentPixels: number;
  visibleHeightPixels: number;
  renderedVisibleHeightRatio: number;
  className: string;
  renderedCanvasTranslatePercent: number;
};

export const DEFAULT_STANDEE_FOOTING = {
  topTransparentPixels: 0,
  bottomTransparentPixels: 0,
  visibleHeightPixels: 0,
  renderedVisibleHeightRatio: 1,
  className: "translate-y-0",
  renderedCanvasTranslatePercent: 0,
} as const satisfies StandeeFooting;

export const STANDEE_FOOTING_BY_CUTOUT_PATH: Readonly<Record<string, StandeeFooting>> = {
  "/assets/portraits/aldric-vale-marsh/portrait-angry.png": {
    topTransparentPixels: 120,
    bottomTransparentPixels: 79,
    visibleHeightPixels: 1645,
    renderedVisibleHeightRatio: 0.8921,
    className: "translate-y-[4.28%]",
    renderedCanvasTranslatePercent: 4.28,
  },
  "/assets/portraits/aldric-vale-marsh/portrait-confused.png": {
    topTransparentPixels: 45,
    bottomTransparentPixels: 30,
    visibleHeightPixels: 1750,
    renderedVisibleHeightRatio: 0.9589,
    className: "translate-y-[1.64%]",
    renderedCanvasTranslatePercent: 1.64,
  },
  "/assets/portraits/aldric-vale-marsh/portrait-flirty.png": {
    topTransparentPixels: 37,
    bottomTransparentPixels: 17,
    visibleHeightPixels: 1771,
    renderedVisibleHeightRatio: 0.9704,
    className: "translate-y-[0.93%]",
    renderedCanvasTranslatePercent: 0.93,
  },
  "/assets/portraits/aldric-vale-marsh/portrait.png": {
    topTransparentPixels: 46,
    bottomTransparentPixels: 35,
    visibleHeightPixels: 1739,
    renderedVisibleHeightRatio: 0.9555,
    className: "translate-y-[1.92%]",
    renderedCanvasTranslatePercent: 1.92,
  },
  "/assets/portraits/alex-yoon/portrait-angry.png": {
    topTransparentPixels: 34,
    bottomTransparentPixels: 40,
    visibleHeightPixels: 1700,
    renderedVisibleHeightRatio: 0.9583,
    className: "translate-y-[2.25%]",
    renderedCanvasTranslatePercent: 2.25,
  },
  "/assets/portraits/alex-yoon/portrait-confused.png": {
    topTransparentPixels: 41,
    bottomTransparentPixels: 76,
    visibleHeightPixels: 1657,
    renderedVisibleHeightRatio: 0.934,
    className: "translate-y-[4.28%]",
    renderedCanvasTranslatePercent: 4.28,
  },
  "/assets/portraits/alex-yoon/portrait-flirty.png": {
    topTransparentPixels: 38,
    bottomTransparentPixels: 52,
    visibleHeightPixels: 1684,
    renderedVisibleHeightRatio: 0.9493,
    className: "translate-y-[2.93%]",
    renderedCanvasTranslatePercent: 2.93,
  },
  "/assets/portraits/alex-yoon/portrait.png": {
    topTransparentPixels: 38,
    bottomTransparentPixels: 38,
    visibleHeightPixels: 1698,
    renderedVisibleHeightRatio: 0.9572,
    className: "translate-y-[2.14%]",
    renderedCanvasTranslatePercent: 2.14,
  },
  "/assets/portraits/anansi/portrait-angry.png": {
    topTransparentPixels: 8,
    bottomTransparentPixels: 0,
    visibleHeightPixels: 1766,
    renderedVisibleHeightRatio: 0.9955,
    className: "translate-y-0",
    renderedCanvasTranslatePercent: 0,
  },
  "/assets/portraits/anansi/portrait-confused.png": {
    topTransparentPixels: 19,
    bottomTransparentPixels: 17,
    visibleHeightPixels: 1738,
    renderedVisibleHeightRatio: 0.9797,
    className: "translate-y-[0.96%]",
    renderedCanvasTranslatePercent: 0.96,
  },
  "/assets/portraits/anansi/portrait-flirty.png": {
    topTransparentPixels: 12,
    bottomTransparentPixels: 15,
    visibleHeightPixels: 1747,
    renderedVisibleHeightRatio: 0.9848,
    className: "translate-y-[0.85%]",
    renderedCanvasTranslatePercent: 0.85,
  },
  "/assets/portraits/anansi/portrait.png": {
    topTransparentPixels: 6,
    bottomTransparentPixels: 10,
    visibleHeightPixels: 1758,
    renderedVisibleHeightRatio: 0.991,
    className: "translate-y-[0.56%]",
    renderedCanvasTranslatePercent: 0.56,
  },
  "/assets/portraits/anubis/portrait-angry.png": {
    topTransparentPixels: 10,
    bottomTransparentPixels: 38,
    visibleHeightPixels: 1726,
    renderedVisibleHeightRatio: 0.9729,
    className: "translate-y-[2.14%]",
    renderedCanvasTranslatePercent: 2.14,
  },
  "/assets/portraits/anubis/portrait-confused.png": {
    topTransparentPixels: 15,
    bottomTransparentPixels: 14,
    visibleHeightPixels: 1745,
    renderedVisibleHeightRatio: 0.9837,
    className: "translate-y-[0.79%]",
    renderedCanvasTranslatePercent: 0.79,
  },
  "/assets/portraits/anubis/portrait-flirty.png": {
    topTransparentPixels: 12,
    bottomTransparentPixels: 48,
    visibleHeightPixels: 1714,
    renderedVisibleHeightRatio: 0.9662,
    className: "translate-y-[2.71%]",
    renderedCanvasTranslatePercent: 2.71,
  },
  "/assets/portraits/anubis/portrait.png": {
    topTransparentPixels: 3,
    bottomTransparentPixels: 0,
    visibleHeightPixels: 1771,
    renderedVisibleHeightRatio: 0.9983,
    className: "translate-y-0",
    renderedCanvasTranslatePercent: 0,
  },
  "/assets/portraits/bai-wenshu/portrait-angry.png": {
    topTransparentPixels: 21,
    bottomTransparentPixels: 0,
    visibleHeightPixels: 1800,
    renderedVisibleHeightRatio: 0.9885,
    className: "translate-y-0",
    renderedCanvasTranslatePercent: 0,
  },
  "/assets/portraits/bai-wenshu/portrait-confused.png": {
    topTransparentPixels: 28,
    bottomTransparentPixels: 25,
    visibleHeightPixels: 1770,
    renderedVisibleHeightRatio: 0.9709,
    className: "translate-y-[1.37%]",
    renderedCanvasTranslatePercent: 1.37,
  },
  "/assets/portraits/bai-wenshu/portrait-flirty.png": {
    topTransparentPixels: 71,
    bottomTransparentPixels: 71,
    visibleHeightPixels: 1679,
    renderedVisibleHeightRatio: 0.922,
    className: "translate-y-[3.90%]",
    renderedCanvasTranslatePercent: 3.9,
  },
  "/assets/portraits/bai-wenshu/portrait.png": {
    topTransparentPixels: 21,
    bottomTransparentPixels: 9,
    visibleHeightPixels: 1791,
    renderedVisibleHeightRatio: 0.9835,
    className: "translate-y-[0.49%]",
    renderedCanvasTranslatePercent: 0.49,
  },
  "/assets/portraits/brady-strait/portrait-angry.png": {
    topTransparentPixels: 14,
    bottomTransparentPixels: 100,
    visibleHeightPixels: 1659,
    renderedVisibleHeightRatio: 0.9352,
    className: "translate-y-[5.64%]",
    renderedCanvasTranslatePercent: 5.64,
  },
  "/assets/portraits/brady-strait/portrait-confused.png": {
    topTransparentPixels: 24,
    bottomTransparentPixels: 27,
    visibleHeightPixels: 1723,
    renderedVisibleHeightRatio: 0.9713,
    className: "translate-y-[1.52%]",
    renderedCanvasTranslatePercent: 1.52,
  },
  "/assets/portraits/brady-strait/portrait-flirty.png": {
    topTransparentPixels: 24,
    bottomTransparentPixels: 71,
    visibleHeightPixels: 1679,
    renderedVisibleHeightRatio: 0.9464,
    className: "translate-y-[4.00%]",
    renderedCanvasTranslatePercent: 4,
  },
  "/assets/portraits/brady-strait/portrait.png": {
    topTransparentPixels: 24,
    bottomTransparentPixels: 20,
    visibleHeightPixels: 1729,
    renderedVisibleHeightRatio: 0.9746,
    className: "translate-y-[1.13%]",
    renderedCanvasTranslatePercent: 1.13,
  },
  "/assets/portraits/calvin-hewes/portrait-angry.png": {
    topTransparentPixels: 30,
    bottomTransparentPixels: 20,
    visibleHeightPixels: 1692,
    renderedVisibleHeightRatio: 0.9369,
    className: "translate-y-[1.11%]",
    renderedCanvasTranslatePercent: 1.11,
  },
  "/assets/portraits/calvin-hewes/portrait-confused.png": {
    topTransparentPixels: 27,
    bottomTransparentPixels: 54,
    visibleHeightPixels: 1662,
    renderedVisibleHeightRatio: 0.9213,
    className: "translate-y-[2.99%]",
    renderedCanvasTranslatePercent: 2.99,
  },
  "/assets/portraits/calvin-hewes/portrait-flirty.png": {
    topTransparentPixels: 59,
    bottomTransparentPixels: 29,
    visibleHeightPixels: 1686,
    renderedVisibleHeightRatio: 0.9504,
    className: "translate-y-[1.63%]",
    renderedCanvasTranslatePercent: 1.63,
  },
  "/assets/portraits/calvin-hewes/portrait.png": {
    topTransparentPixels: 34,
    bottomTransparentPixels: 13,
    visibleHeightPixels: 1727,
    renderedVisibleHeightRatio: 0.9735,
    className: "translate-y-[0.73%]",
    renderedCanvasTranslatePercent: 0.73,
  },
  "/assets/portraits/cassie-conners/portrait-angry.png": {
    topTransparentPixels: 22,
    bottomTransparentPixels: 161,
    visibleHeightPixels: 1591,
    renderedVisibleHeightRatio: 0.8968,
    className: "translate-y-[9.08%]",
    renderedCanvasTranslatePercent: 9.08,
  },
  "/assets/portraits/cassie-conners/portrait-confused.png": {
    topTransparentPixels: 48,
    bottomTransparentPixels: 104,
    visibleHeightPixels: 1622,
    renderedVisibleHeightRatio: 0.9143,
    className: "translate-y-[5.86%]",
    renderedCanvasTranslatePercent: 5.86,
  },
  "/assets/portraits/cassie-conners/portrait-flirty.png": {
    topTransparentPixels: 58,
    bottomTransparentPixels: 60,
    visibleHeightPixels: 1656,
    renderedVisibleHeightRatio: 0.9335,
    className: "translate-y-[3.38%]",
    renderedCanvasTranslatePercent: 3.38,
  },
  "/assets/portraits/cassie-conners/portrait.png": {
    topTransparentPixels: 44,
    bottomTransparentPixels: 150,
    visibleHeightPixels: 1580,
    renderedVisibleHeightRatio: 0.8906,
    className: "translate-y-[8.46%]",
    renderedCanvasTranslatePercent: 8.46,
  },
  "/assets/portraits/cha-yusung/portrait-angry.png": {
    topTransparentPixels: 20,
    bottomTransparentPixels: 15,
    visibleHeightPixels: 1739,
    renderedVisibleHeightRatio: 0.9803,
    className: "translate-y-[0.85%]",
    renderedCanvasTranslatePercent: 0.85,
  },
  "/assets/portraits/cha-yusung/portrait-confused.png": {
    topTransparentPixels: 62,
    bottomTransparentPixels: 31,
    visibleHeightPixels: 1681,
    renderedVisibleHeightRatio: 0.9476,
    className: "translate-y-[1.75%]",
    renderedCanvasTranslatePercent: 1.75,
  },
  "/assets/portraits/cha-yusung/portrait-flirty.png": {
    topTransparentPixels: 29,
    bottomTransparentPixels: 55,
    visibleHeightPixels: 1690,
    renderedVisibleHeightRatio: 0.9526,
    className: "translate-y-[3.10%]",
    renderedCanvasTranslatePercent: 3.1,
  },
  "/assets/portraits/cha-yusung/portrait.png": {
    topTransparentPixels: 31,
    bottomTransparentPixels: 55,
    visibleHeightPixels: 1688,
    renderedVisibleHeightRatio: 0.9515,
    className: "translate-y-[3.10%]",
    renderedCanvasTranslatePercent: 3.1,
  },
  "/assets/portraits/cthala/portrait-angry.png": {
    topTransparentPixels: 38,
    bottomTransparentPixels: 69,
    visibleHeightPixels: 1667,
    renderedVisibleHeightRatio: 0.9397,
    className: "translate-y-[3.89%]",
    renderedCanvasTranslatePercent: 3.89,
  },
  "/assets/portraits/cthala/portrait-confused.png": {
    topTransparentPixels: 52,
    bottomTransparentPixels: 38,
    visibleHeightPixels: 1684,
    renderedVisibleHeightRatio: 0.9493,
    className: "translate-y-[2.14%]",
    renderedCanvasTranslatePercent: 2.14,
  },
  "/assets/portraits/cthala/portrait-flirty.png": {
    topTransparentPixels: 31,
    bottomTransparentPixels: 27,
    visibleHeightPixels: 1716,
    renderedVisibleHeightRatio: 0.9673,
    className: "translate-y-[1.52%]",
    renderedCanvasTranslatePercent: 1.52,
  },
  "/assets/portraits/cthala/portrait.png": {
    topTransparentPixels: 19,
    bottomTransparentPixels: 22,
    visibleHeightPixels: 1733,
    renderedVisibleHeightRatio: 0.9769,
    className: "translate-y-[1.24%]",
    renderedCanvasTranslatePercent: 1.24,
  },
  "/assets/portraits/decimus-marius-tullio/portrait-angry.png": {
    topTransparentPixels: 27,
    bottomTransparentPixels: 64,
    visibleHeightPixels: 1683,
    renderedVisibleHeightRatio: 0.9487,
    className: "translate-y-[3.61%]",
    renderedCanvasTranslatePercent: 3.61,
  },
  "/assets/portraits/decimus-marius-tullio/portrait-confused.png": {
    topTransparentPixels: 20,
    bottomTransparentPixels: 80,
    visibleHeightPixels: 1644,
    renderedVisibleHeightRatio: 0.9113,
    className: "translate-y-[4.43%]",
    renderedCanvasTranslatePercent: 4.43,
  },
  "/assets/portraits/decimus-marius-tullio/portrait-flirty.png": {
    topTransparentPixels: 48,
    bottomTransparentPixels: 57,
    visibleHeightPixels: 1668,
    renderedVisibleHeightRatio: 0.9402,
    className: "translate-y-[3.21%]",
    renderedCanvasTranslatePercent: 3.21,
  },
  "/assets/portraits/decimus-marius-tullio/portrait.png": {
    topTransparentPixels: 32,
    bottomTransparentPixels: 25,
    visibleHeightPixels: 1687,
    renderedVisibleHeightRatio: 0.9351,
    className: "translate-y-[1.39%]",
    renderedCanvasTranslatePercent: 1.39,
  },
  "/assets/portraits/derek-halsey/portrait-angry.png": {
    topTransparentPixels: 43,
    bottomTransparentPixels: 32,
    visibleHeightPixels: 1699,
    renderedVisibleHeightRatio: 0.9577,
    className: "translate-y-[1.80%]",
    renderedCanvasTranslatePercent: 1.8,
  },
  "/assets/portraits/derek-halsey/portrait-confused.png": {
    topTransparentPixels: 62,
    bottomTransparentPixels: 51,
    visibleHeightPixels: 1661,
    renderedVisibleHeightRatio: 0.9363,
    className: "translate-y-[2.87%]",
    renderedCanvasTranslatePercent: 2.87,
  },
  "/assets/portraits/derek-halsey/portrait-flirty.png": {
    topTransparentPixels: 48,
    bottomTransparentPixels: 43,
    visibleHeightPixels: 1683,
    renderedVisibleHeightRatio: 0.9487,
    className: "translate-y-[2.42%]",
    renderedCanvasTranslatePercent: 2.42,
  },
  "/assets/portraits/derek-halsey/portrait.png": {
    topTransparentPixels: 45,
    bottomTransparentPixels: 52,
    visibleHeightPixels: 1677,
    renderedVisibleHeightRatio: 0.9453,
    className: "translate-y-[2.93%]",
    renderedCanvasTranslatePercent: 2.93,
  },
  "/assets/portraits/eleanor-ash/portrait-angry.png": {
    topTransparentPixels: 214,
    bottomTransparentPixels: 27,
    visibleHeightPixels: 1533,
    renderedVisibleHeightRatio: 0.8641,
    className: "translate-y-[1.52%]",
    renderedCanvasTranslatePercent: 1.52,
  },
  "/assets/portraits/eleanor-ash/portrait-confused.png": {
    topTransparentPixels: 41,
    bottomTransparentPixels: 164,
    visibleHeightPixels: 1565,
    renderedVisibleHeightRatio: 0.8802,
    className: "translate-y-[9.22%]",
    renderedCanvasTranslatePercent: 9.22,
  },
  "/assets/portraits/eleanor-ash/portrait-flirty.png": {
    topTransparentPixels: 161,
    bottomTransparentPixels: 154,
    visibleHeightPixels: 1459,
    renderedVisibleHeightRatio: 0.8224,
    className: "translate-y-[8.68%]",
    renderedCanvasTranslatePercent: 8.68,
  },
  "/assets/portraits/eleanor-ash/portrait.png": {
    topTransparentPixels: 29,
    bottomTransparentPixels: 26,
    visibleHeightPixels: 1719,
    renderedVisibleHeightRatio: 0.969,
    className: "translate-y-[1.47%]",
    renderedCanvasTranslatePercent: 1.47,
  },
  "/assets/portraits/epsy/portrait-angry.png": {
    topTransparentPixels: 107,
    bottomTransparentPixels: 52,
    visibleHeightPixels: 1615,
    renderedVisibleHeightRatio: 0.9104,
    className: "translate-y-[2.93%]",
    renderedCanvasTranslatePercent: 2.93,
  },
  "/assets/portraits/epsy/portrait-confused.png": {
    topTransparentPixels: 20,
    bottomTransparentPixels: 17,
    visibleHeightPixels: 1737,
    renderedVisibleHeightRatio: 0.9791,
    className: "translate-y-[0.96%]",
    renderedCanvasTranslatePercent: 0.96,
  },
  "/assets/portraits/epsy/portrait-flirty.png": {
    topTransparentPixels: 20,
    bottomTransparentPixels: 1,
    visibleHeightPixels: 1753,
    renderedVisibleHeightRatio: 0.9882,
    className: "translate-y-[0.06%]",
    renderedCanvasTranslatePercent: 0.06,
  },
  "/assets/portraits/epsy/portrait.png": {
    topTransparentPixels: 27,
    bottomTransparentPixels: 57,
    visibleHeightPixels: 1690,
    renderedVisibleHeightRatio: 0.9526,
    className: "translate-y-[3.21%]",
    renderedCanvasTranslatePercent: 3.21,
  },
  "/assets/portraits/gabriel-tan/portrait-angry.png": {
    topTransparentPixels: 66,
    bottomTransparentPixels: 65,
    visibleHeightPixels: 1643,
    renderedVisibleHeightRatio: 0.9262,
    className: "translate-y-[3.66%]",
    renderedCanvasTranslatePercent: 3.66,
  },
  "/assets/portraits/gabriel-tan/portrait-confused.png": {
    topTransparentPixels: 24,
    bottomTransparentPixels: 69,
    visibleHeightPixels: 1681,
    renderedVisibleHeightRatio: 0.9476,
    className: "translate-y-[3.89%]",
    renderedCanvasTranslatePercent: 3.89,
  },
  "/assets/portraits/gabriel-tan/portrait-flirty.png": {
    topTransparentPixels: 17,
    bottomTransparentPixels: 45,
    visibleHeightPixels: 1712,
    renderedVisibleHeightRatio: 0.9651,
    className: "translate-y-[2.54%]",
    renderedCanvasTranslatePercent: 2.54,
  },
  "/assets/portraits/gabriel-tan/portrait.png": {
    topTransparentPixels: 34,
    bottomTransparentPixels: 64,
    visibleHeightPixels: 1676,
    renderedVisibleHeightRatio: 0.9448,
    className: "translate-y-[3.61%]",
    renderedCanvasTranslatePercent: 3.61,
  },
  "/assets/portraits/gideon-glass/portrait-angry.png": {
    topTransparentPixels: 38,
    bottomTransparentPixels: 52,
    visibleHeightPixels: 1684,
    renderedVisibleHeightRatio: 0.9493,
    className: "translate-y-[2.93%]",
    renderedCanvasTranslatePercent: 2.93,
  },
  "/assets/portraits/gideon-glass/portrait-confused.png": {
    topTransparentPixels: 40,
    bottomTransparentPixels: 69,
    visibleHeightPixels: 1665,
    renderedVisibleHeightRatio: 0.9386,
    className: "translate-y-[3.89%]",
    renderedCanvasTranslatePercent: 3.89,
  },
  "/assets/portraits/gideon-glass/portrait-flirty.png": {
    topTransparentPixels: 26,
    bottomTransparentPixels: 24,
    visibleHeightPixels: 1724,
    renderedVisibleHeightRatio: 0.9718,
    className: "translate-y-[1.35%]",
    renderedCanvasTranslatePercent: 1.35,
  },
  "/assets/portraits/gideon-glass/portrait.png": {
    topTransparentPixels: 29,
    bottomTransparentPixels: 29,
    visibleHeightPixels: 1716,
    renderedVisibleHeightRatio: 0.9673,
    className: "translate-y-[1.63%]",
    renderedCanvasTranslatePercent: 1.63,
  },
  "/assets/portraits/idris-mahari/portrait-angry.png": {
    topTransparentPixels: 24,
    bottomTransparentPixels: 31,
    visibleHeightPixels: 1719,
    renderedVisibleHeightRatio: 0.969,
    className: "translate-y-[1.75%]",
    renderedCanvasTranslatePercent: 1.75,
  },
  "/assets/portraits/idris-mahari/portrait-confused.png": {
    topTransparentPixels: 34,
    bottomTransparentPixels: 17,
    visibleHeightPixels: 1723,
    renderedVisibleHeightRatio: 0.9713,
    className: "translate-y-[0.96%]",
    renderedCanvasTranslatePercent: 0.96,
  },
  "/assets/portraits/idris-mahari/portrait-flirty.png": {
    topTransparentPixels: 8,
    bottomTransparentPixels: 24,
    visibleHeightPixels: 1742,
    renderedVisibleHeightRatio: 0.982,
    className: "translate-y-[1.35%]",
    renderedCanvasTranslatePercent: 1.35,
  },
  "/assets/portraits/idris-mahari/portrait.png": {
    topTransparentPixels: 13,
    bottomTransparentPixels: 8,
    visibleHeightPixels: 1753,
    renderedVisibleHeightRatio: 0.9882,
    className: "translate-y-[0.45%]",
    renderedCanvasTranslatePercent: 0.45,
  },
  "/assets/portraits/imani-wallace/portrait-angry.png": {
    topTransparentPixels: 14,
    bottomTransparentPixels: 10,
    visibleHeightPixels: 1750,
    renderedVisibleHeightRatio: 0.9865,
    className: "translate-y-[0.56%]",
    renderedCanvasTranslatePercent: 0.56,
  },
  "/assets/portraits/imani-wallace/portrait-confused.png": {
    topTransparentPixels: 17,
    bottomTransparentPixels: 31,
    visibleHeightPixels: 1726,
    renderedVisibleHeightRatio: 0.9729,
    className: "translate-y-[1.75%]",
    renderedCanvasTranslatePercent: 1.75,
  },
  "/assets/portraits/imani-wallace/portrait-flirty.png": {
    topTransparentPixels: 14,
    bottomTransparentPixels: 24,
    visibleHeightPixels: 1736,
    renderedVisibleHeightRatio: 0.9786,
    className: "translate-y-[1.35%]",
    renderedCanvasTranslatePercent: 1.35,
  },
  "/assets/portraits/imani-wallace/portrait.png": {
    topTransparentPixels: 15,
    bottomTransparentPixels: 8,
    visibleHeightPixels: 1751,
    renderedVisibleHeightRatio: 0.987,
    className: "translate-y-[0.45%]",
    renderedCanvasTranslatePercent: 0.45,
  },
  "/assets/portraits/jenna-pike/portrait-angry.png": {
    topTransparentPixels: 83,
    bottomTransparentPixels: 146,
    visibleHeightPixels: 1555,
    renderedVisibleHeightRatio: 0.8716,
    className: "translate-y-[8.18%]",
    renderedCanvasTranslatePercent: 8.18,
  },
  "/assets/portraits/jenna-pike/portrait-confused.png": {
    topTransparentPixels: 114,
    bottomTransparentPixels: 194,
    visibleHeightPixels: 1500,
    renderedVisibleHeightRatio: 0.8296,
    className: "translate-y-[10.73%]",
    renderedCanvasTranslatePercent: 10.73,
  },
  "/assets/portraits/jenna-pike/portrait-flirty.png": {
    topTransparentPixels: 56,
    bottomTransparentPixels: 48,
    visibleHeightPixels: 1720,
    renderedVisibleHeightRatio: 0.943,
    className: "translate-y-[2.63%]",
    renderedCanvasTranslatePercent: 2.63,
  },
  "/assets/portraits/jenna-pike/portrait.png": {
    topTransparentPixels: 70,
    bottomTransparentPixels: 71,
    visibleHeightPixels: 1683,
    renderedVisibleHeightRatio: 0.9227,
    className: "translate-y-[3.89%]",
    renderedCanvasTranslatePercent: 3.89,
  },
  "/assets/portraits/junie-marrow/portrait-angry.png": {
    topTransparentPixels: 92,
    bottomTransparentPixels: 201,
    visibleHeightPixels: 1481,
    renderedVisibleHeightRatio: 0.8348,
    className: "translate-y-[11.33%]",
    renderedCanvasTranslatePercent: 11.33,
  },
  "/assets/portraits/junie-marrow/portrait-confused.png": {
    topTransparentPixels: 93,
    bottomTransparentPixels: 202,
    visibleHeightPixels: 1479,
    renderedVisibleHeightRatio: 0.8337,
    className: "translate-y-[11.39%]",
    renderedCanvasTranslatePercent: 11.39,
  },
  "/assets/portraits/junie-marrow/portrait-flirty.png": {
    topTransparentPixels: 93,
    bottomTransparentPixels: 225,
    visibleHeightPixels: 1456,
    renderedVisibleHeightRatio: 0.8207,
    className: "translate-y-[12.68%]",
    renderedCanvasTranslatePercent: 12.68,
  },
  "/assets/portraits/junie-marrow/portrait.png": {
    topTransparentPixels: 100,
    bottomTransparentPixels: 277,
    visibleHeightPixels: 1397,
    renderedVisibleHeightRatio: 0.7875,
    className: "translate-y-[15.61%]",
    renderedCanvasTranslatePercent: 15.61,
  },
  "/assets/portraits/kade-sumner/portrait-angry.png": {
    topTransparentPixels: 31,
    bottomTransparentPixels: 88,
    visibleHeightPixels: 1655,
    renderedVisibleHeightRatio: 0.9329,
    className: "translate-y-[4.96%]",
    renderedCanvasTranslatePercent: 4.96,
  },
  "/assets/portraits/kade-sumner/portrait-confused.png": {
    topTransparentPixels: 52,
    bottomTransparentPixels: 52,
    visibleHeightPixels: 1568,
    renderedVisibleHeightRatio: 0.8332,
    className: "translate-y-[2.76%]",
    renderedCanvasTranslatePercent: 2.76,
  },
  "/assets/portraits/kade-sumner/portrait-flirty.png": {
    topTransparentPixels: 29,
    bottomTransparentPixels: 50,
    visibleHeightPixels: 1695,
    renderedVisibleHeightRatio: 0.9555,
    className: "translate-y-[2.82%]",
    renderedCanvasTranslatePercent: 2.82,
  },
  "/assets/portraits/kade-sumner/portrait.png": {
    topTransparentPixels: 42,
    bottomTransparentPixels: 46,
    visibleHeightPixels: 1733,
    renderedVisibleHeightRatio: 0.9517,
    className: "translate-y-[2.53%]",
    renderedCanvasTranslatePercent: 2.53,
  },
  "/assets/portraits/maeve/portrait-angry.png": {
    topTransparentPixels: 62,
    bottomTransparentPixels: 62,
    visibleHeightPixels: 1650,
    renderedVisibleHeightRatio: 0.9301,
    className: "translate-y-[3.49%]",
    renderedCanvasTranslatePercent: 3.49,
  },
  "/assets/portraits/maeve/portrait-confused.png": {
    topTransparentPixels: 64,
    bottomTransparentPixels: 105,
    visibleHeightPixels: 1605,
    renderedVisibleHeightRatio: 0.9047,
    className: "translate-y-[5.92%]",
    renderedCanvasTranslatePercent: 5.92,
  },
  "/assets/portraits/maeve/portrait-flirty.png": {
    topTransparentPixels: 51,
    bottomTransparentPixels: 62,
    visibleHeightPixels: 1661,
    renderedVisibleHeightRatio: 0.9363,
    className: "translate-y-[3.49%]",
    renderedCanvasTranslatePercent: 3.49,
  },
  "/assets/portraits/maeve/portrait.png": {
    topTransparentPixels: 85,
    bottomTransparentPixels: 107,
    visibleHeightPixels: 1582,
    renderedVisibleHeightRatio: 0.8918,
    className: "translate-y-[6.03%]",
    renderedCanvasTranslatePercent: 6.03,
  },
  "/assets/portraits/marcus-pellish/portrait-angry.png": {
    topTransparentPixels: 35,
    bottomTransparentPixels: 107,
    visibleHeightPixels: 1605,
    renderedVisibleHeightRatio: 0.8917,
    className: "translate-y-[5.94%]",
    renderedCanvasTranslatePercent: 5.94,
  },
  "/assets/portraits/marcus-pellish/portrait-confused.png": {
    topTransparentPixels: 31,
    bottomTransparentPixels: 60,
    visibleHeightPixels: 1665,
    renderedVisibleHeightRatio: 0.9302,
    className: "translate-y-[3.35%]",
    renderedCanvasTranslatePercent: 3.35,
  },
  "/assets/portraits/marcus-pellish/portrait-flirty.png": {
    topTransparentPixels: 41,
    bottomTransparentPixels: 128,
    visibleHeightPixels: 1582,
    renderedVisibleHeightRatio: 0.8808,
    className: "translate-y-[7.13%]",
    renderedCanvasTranslatePercent: 7.13,
  },
  "/assets/portraits/marcus-pellish/portrait.png": {
    topTransparentPixels: 17,
    bottomTransparentPixels: 63,
    visibleHeightPixels: 1672,
    renderedVisibleHeightRatio: 0.932,
    className: "translate-y-[3.51%]",
    renderedCanvasTranslatePercent: 3.51,
  },
  "/assets/portraits/mei-sato/portrait-angry.png": {
    topTransparentPixels: 86,
    bottomTransparentPixels: 72,
    visibleHeightPixels: 1688,
    renderedVisibleHeightRatio: 0.9144,
    className: "translate-y-[3.90%]",
    renderedCanvasTranslatePercent: 3.9,
  },
  "/assets/portraits/mei-sato/portrait-confused.png": {
    topTransparentPixels: 108,
    bottomTransparentPixels: 83,
    visibleHeightPixels: 1656,
    renderedVisibleHeightRatio: 0.8966,
    className: "translate-y-[4.49%]",
    renderedCanvasTranslatePercent: 4.49,
  },
  "/assets/portraits/mei-sato/portrait-flirty.png": {
    topTransparentPixels: 72,
    bottomTransparentPixels: 39,
    visibleHeightPixels: 1735,
    renderedVisibleHeightRatio: 0.9399,
    className: "translate-y-[2.11%]",
    renderedCanvasTranslatePercent: 2.11,
  },
  "/assets/portraits/mei-sato/portrait.png": {
    topTransparentPixels: 66,
    bottomTransparentPixels: 54,
    visibleHeightPixels: 1727,
    renderedVisibleHeightRatio: 0.935,
    className: "translate-y-[2.92%]",
    renderedCanvasTranslatePercent: 2.92,
  },
  "/assets/portraits/meridian-vale/portrait-angry.png": {
    topTransparentPixels: 19,
    bottomTransparentPixels: 22,
    visibleHeightPixels: 1733,
    renderedVisibleHeightRatio: 0.9769,
    className: "translate-y-[1.24%]",
    renderedCanvasTranslatePercent: 1.24,
  },
  "/assets/portraits/meridian-vale/portrait-confused.png": {
    topTransparentPixels: 19,
    bottomTransparentPixels: 45,
    visibleHeightPixels: 1710,
    renderedVisibleHeightRatio: 0.9639,
    className: "translate-y-[2.54%]",
    renderedCanvasTranslatePercent: 2.54,
  },
  "/assets/portraits/meridian-vale/portrait-flirty.png": {
    topTransparentPixels: 10,
    bottomTransparentPixels: 19,
    visibleHeightPixels: 1745,
    renderedVisibleHeightRatio: 0.9837,
    className: "translate-y-[1.07%]",
    renderedCanvasTranslatePercent: 1.07,
  },
  "/assets/portraits/meridian-vale/portrait.png": {
    topTransparentPixels: 15,
    bottomTransparentPixels: 6,
    visibleHeightPixels: 1753,
    renderedVisibleHeightRatio: 0.9882,
    className: "translate-y-[0.34%]",
    renderedCanvasTranslatePercent: 0.34,
  },
  "/assets/portraits/mira-park/portrait-angry.png": {
    topTransparentPixels: 48,
    bottomTransparentPixels: 10,
    visibleHeightPixels: 1716,
    renderedVisibleHeightRatio: 0.9673,
    className: "translate-y-[0.56%]",
    renderedCanvasTranslatePercent: 0.56,
  },
  "/assets/portraits/mira-park/portrait-confused.png": {
    topTransparentPixels: 43,
    bottomTransparentPixels: 83,
    visibleHeightPixels: 1648,
    renderedVisibleHeightRatio: 0.929,
    className: "translate-y-[4.68%]",
    renderedCanvasTranslatePercent: 4.68,
  },
  "/assets/portraits/mira-park/portrait-flirty.png": {
    topTransparentPixels: 57,
    bottomTransparentPixels: 41,
    visibleHeightPixels: 1676,
    renderedVisibleHeightRatio: 0.9448,
    className: "translate-y-[2.31%]",
    renderedCanvasTranslatePercent: 2.31,
  },
  "/assets/portraits/mira-park/portrait.png": {
    topTransparentPixels: 55,
    bottomTransparentPixels: 15,
    visibleHeightPixels: 1704,
    renderedVisibleHeightRatio: 0.9605,
    className: "translate-y-[0.85%]",
    renderedCanvasTranslatePercent: 0.85,
  },
  "/assets/portraits/mr-whiskers/portrait-angry.png": {
    topTransparentPixels: 17,
    bottomTransparentPixels: 24,
    visibleHeightPixels: 1733,
    renderedVisibleHeightRatio: 0.9769,
    className: "translate-y-[1.35%]",
    renderedCanvasTranslatePercent: 1.35,
  },
  "/assets/portraits/mr-whiskers/portrait-confused.png": {
    topTransparentPixels: 14,
    bottomTransparentPixels: 26,
    visibleHeightPixels: 1734,
    renderedVisibleHeightRatio: 0.9775,
    className: "translate-y-[1.47%]",
    renderedCanvasTranslatePercent: 1.47,
  },
  "/assets/portraits/mr-whiskers/portrait-flirty.png": {
    topTransparentPixels: 50,
    bottomTransparentPixels: 38,
    visibleHeightPixels: 1686,
    renderedVisibleHeightRatio: 0.9504,
    className: "translate-y-[2.14%]",
    renderedCanvasTranslatePercent: 2.14,
  },
  "/assets/portraits/mr-whiskers/portrait.png": {
    topTransparentPixels: 71,
    bottomTransparentPixels: 1,
    visibleHeightPixels: 1702,
    renderedVisibleHeightRatio: 0.9594,
    className: "translate-y-[0.06%]",
    renderedCanvasTranslatePercent: 0.06,
  },
  "/assets/portraits/naia-velorae/portrait-angry.png": {
    topTransparentPixels: 100,
    bottomTransparentPixels: 57,
    visibleHeightPixels: 1617,
    renderedVisibleHeightRatio: 0.9115,
    className: "translate-y-[3.21%]",
    renderedCanvasTranslatePercent: 3.21,
  },
  "/assets/portraits/naia-velorae/portrait-confused.png": {
    topTransparentPixels: 17,
    bottomTransparentPixels: 31,
    visibleHeightPixels: 1726,
    renderedVisibleHeightRatio: 0.9729,
    className: "translate-y-[1.75%]",
    renderedCanvasTranslatePercent: 1.75,
  },
  "/assets/portraits/naia-velorae/portrait-flirty.png": {
    topTransparentPixels: 19,
    bottomTransparentPixels: 100,
    visibleHeightPixels: 1655,
    renderedVisibleHeightRatio: 0.9329,
    className: "translate-y-[5.64%]",
    renderedCanvasTranslatePercent: 5.64,
  },
  "/assets/portraits/naia-velorae/portrait.png": {
    topTransparentPixels: 13,
    bottomTransparentPixels: 46,
    visibleHeightPixels: 1715,
    renderedVisibleHeightRatio: 0.9667,
    className: "translate-y-[2.59%]",
    renderedCanvasTranslatePercent: 2.59,
  },
  "/assets/portraits/nawal-marrash/portrait-angry.png": {
    topTransparentPixels: 55,
    bottomTransparentPixels: 53,
    visibleHeightPixels: 1666,
    renderedVisibleHeightRatio: 0.9391,
    className: "translate-y-[2.99%]",
    renderedCanvasTranslatePercent: 2.99,
  },
  "/assets/portraits/nawal-marrash/portrait-confused.png": {
    topTransparentPixels: 45,
    bottomTransparentPixels: 17,
    visibleHeightPixels: 1712,
    renderedVisibleHeightRatio: 0.9651,
    className: "translate-y-[0.96%]",
    renderedCanvasTranslatePercent: 0.96,
  },
  "/assets/portraits/nawal-marrash/portrait-flirty.png": {
    topTransparentPixels: 55,
    bottomTransparentPixels: 29,
    visibleHeightPixels: 1690,
    renderedVisibleHeightRatio: 0.9526,
    className: "translate-y-[1.63%]",
    renderedCanvasTranslatePercent: 1.63,
  },
  "/assets/portraits/nawal-marrash/portrait.png": {
    topTransparentPixels: 51,
    bottomTransparentPixels: 41,
    visibleHeightPixels: 1682,
    renderedVisibleHeightRatio: 0.9481,
    className: "translate-y-[2.31%]",
    renderedCanvasTranslatePercent: 2.31,
  },
  "/assets/portraits/noah-kim/portrait-angry.png": {
    topTransparentPixels: 17,
    bottomTransparentPixels: 36,
    visibleHeightPixels: 1721,
    renderedVisibleHeightRatio: 0.9701,
    className: "translate-y-[2.03%]",
    renderedCanvasTranslatePercent: 2.03,
  },
  "/assets/portraits/noah-kim/portrait-confused.png": {
    topTransparentPixels: 41,
    bottomTransparentPixels: 51,
    visibleHeightPixels: 1682,
    renderedVisibleHeightRatio: 0.9481,
    className: "translate-y-[2.87%]",
    renderedCanvasTranslatePercent: 2.87,
  },
  "/assets/portraits/noah-kim/portrait-flirty.png": {
    topTransparentPixels: 3,
    bottomTransparentPixels: 88,
    visibleHeightPixels: 1683,
    renderedVisibleHeightRatio: 0.9487,
    className: "translate-y-[4.96%]",
    renderedCanvasTranslatePercent: 4.96,
  },
  "/assets/portraits/noah-kim/portrait.png": {
    topTransparentPixels: 22,
    bottomTransparentPixels: 31,
    visibleHeightPixels: 1721,
    renderedVisibleHeightRatio: 0.9701,
    className: "translate-y-[1.75%]",
    renderedCanvasTranslatePercent: 1.75,
  },
  "/assets/portraits/opal-sunday/portrait-angry.png": {
    topTransparentPixels: 33,
    bottomTransparentPixels: 32,
    visibleHeightPixels: 1709,
    renderedVisibleHeightRatio: 0.9634,
    className: "translate-y-[1.80%]",
    renderedCanvasTranslatePercent: 1.8,
  },
  "/assets/portraits/opal-sunday/portrait-confused.png": {
    topTransparentPixels: 34,
    bottomTransparentPixels: 26,
    visibleHeightPixels: 1714,
    renderedVisibleHeightRatio: 0.9662,
    className: "translate-y-[1.47%]",
    renderedCanvasTranslatePercent: 1.47,
  },
  "/assets/portraits/opal-sunday/portrait-flirty.png": {
    topTransparentPixels: 69,
    bottomTransparentPixels: 51,
    visibleHeightPixels: 1654,
    renderedVisibleHeightRatio: 0.9324,
    className: "translate-y-[2.87%]",
    renderedCanvasTranslatePercent: 2.87,
  },
  "/assets/portraits/opal-sunday/portrait.png": {
    topTransparentPixels: 33,
    bottomTransparentPixels: 90,
    visibleHeightPixels: 1651,
    renderedVisibleHeightRatio: 0.9307,
    className: "translate-y-[5.07%]",
    renderedCanvasTranslatePercent: 5.07,
  },
  "/assets/portraits/reaver/portrait-angry.png": {
    topTransparentPixels: 34,
    bottomTransparentPixels: 58,
    visibleHeightPixels: 1682,
    renderedVisibleHeightRatio: 0.9481,
    className: "translate-y-[3.27%]",
    renderedCanvasTranslatePercent: 3.27,
  },
  "/assets/portraits/reaver/portrait-confused.png": {
    topTransparentPixels: 20,
    bottomTransparentPixels: 20,
    visibleHeightPixels: 1734,
    renderedVisibleHeightRatio: 0.9775,
    className: "translate-y-[1.13%]",
    renderedCanvasTranslatePercent: 1.13,
  },
  "/assets/portraits/reaver/portrait-flirty.png": {
    topTransparentPixels: 84,
    bottomTransparentPixels: 95,
    visibleHeightPixels: 1595,
    renderedVisibleHeightRatio: 0.8991,
    className: "translate-y-[5.36%]",
    renderedCanvasTranslatePercent: 5.36,
  },
  "/assets/portraits/reaver/portrait.png": {
    topTransparentPixels: 27,
    bottomTransparentPixels: 13,
    visibleHeightPixels: 1734,
    renderedVisibleHeightRatio: 0.9775,
    className: "translate-y-[0.73%]",
    renderedCanvasTranslatePercent: 0.73,
  },
  "/assets/portraits/ryan-doyle/portrait-angry.png": {
    topTransparentPixels: 57,
    bottomTransparentPixels: 52,
    visibleHeightPixels: 1665,
    renderedVisibleHeightRatio: 0.9386,
    className: "translate-y-[2.93%]",
    renderedCanvasTranslatePercent: 2.93,
  },
  "/assets/portraits/ryan-doyle/portrait-confused.png": {
    topTransparentPixels: 53,
    bottomTransparentPixels: 50,
    visibleHeightPixels: 1671,
    renderedVisibleHeightRatio: 0.9419,
    className: "translate-y-[2.82%]",
    renderedCanvasTranslatePercent: 2.82,
  },
  "/assets/portraits/ryan-doyle/portrait-flirty.png": {
    topTransparentPixels: 55,
    bottomTransparentPixels: 66,
    visibleHeightPixels: 1653,
    renderedVisibleHeightRatio: 0.9318,
    className: "translate-y-[3.72%]",
    renderedCanvasTranslatePercent: 3.72,
  },
  "/assets/portraits/ryan-doyle/portrait.png": {
    topTransparentPixels: 27,
    bottomTransparentPixels: 55,
    visibleHeightPixels: 1692,
    renderedVisibleHeightRatio: 0.9538,
    className: "translate-y-[3.10%]",
    renderedCanvasTranslatePercent: 3.1,
  },
  "/assets/portraits/sana-karim/portrait-angry.png": {
    topTransparentPixels: 52,
    bottomTransparentPixels: 86,
    visibleHeightPixels: 1705,
    renderedVisibleHeightRatio: 0.9251,
    className: "translate-y-[4.67%]",
    renderedCanvasTranslatePercent: 4.67,
  },
  "/assets/portraits/sana-karim/portrait-confused.png": {
    topTransparentPixels: 68,
    bottomTransparentPixels: 102,
    visibleHeightPixels: 1674,
    renderedVisibleHeightRatio: 0.9078,
    className: "translate-y-[5.53%]",
    renderedCanvasTranslatePercent: 5.53,
  },
  "/assets/portraits/sana-karim/portrait-flirty.png": {
    topTransparentPixels: 46,
    bottomTransparentPixels: 23,
    visibleHeightPixels: 1756,
    renderedVisibleHeightRatio: 0.9622,
    className: "translate-y-[1.26%]",
    renderedCanvasTranslatePercent: 1.26,
  },
  "/assets/portraits/sana-karim/portrait.png": {
    topTransparentPixels: 69,
    bottomTransparentPixels: 58,
    visibleHeightPixels: 1698,
    renderedVisibleHeightRatio: 0.9304,
    className: "translate-y-[3.18%]",
    renderedCanvasTranslatePercent: 3.18,
  },
  "/assets/portraits/sera-vohn/portrait-angry.png": {
    topTransparentPixels: 57,
    bottomTransparentPixels: 172,
    visibleHeightPixels: 1652,
    renderedVisibleHeightRatio: 0.8783,
    className: "translate-y-[9.14%]",
    renderedCanvasTranslatePercent: 9.14,
  },
  "/assets/portraits/sera-vohn/portrait-confused.png": {
    topTransparentPixels: 50,
    bottomTransparentPixels: 118,
    visibleHeightPixels: 1676,
    renderedVisibleHeightRatio: 0.9089,
    className: "translate-y-[6.40%]",
    renderedCanvasTranslatePercent: 6.4,
  },
  "/assets/portraits/sera-vohn/portrait-flirty.png": {
    topTransparentPixels: 60,
    bottomTransparentPixels: 183,
    visibleHeightPixels: 1579,
    renderedVisibleHeightRatio: 0.8666,
    className: "translate-y-[10.04%]",
    renderedCanvasTranslatePercent: 10.04,
  },
  "/assets/portraits/sera-vohn/portrait.png": {
    topTransparentPixels: 26,
    bottomTransparentPixels: 26,
    visibleHeightPixels: 1722,
    renderedVisibleHeightRatio: 0.9707,
    className: "translate-y-[1.47%]",
    renderedCanvasTranslatePercent: 1.47,
  },
  "/assets/portraits/sienna-bae/portrait-angry.png": {
    topTransparentPixels: 59,
    bottomTransparentPixels: 64,
    visibleHeightPixels: 1651,
    renderedVisibleHeightRatio: 0.9307,
    className: "translate-y-[3.61%]",
    renderedCanvasTranslatePercent: 3.61,
  },
  "/assets/portraits/sienna-bae/portrait-confused.png": {
    topTransparentPixels: 69,
    bottomTransparentPixels: 71,
    visibleHeightPixels: 1634,
    renderedVisibleHeightRatio: 0.9211,
    className: "translate-y-[4.00%]",
    renderedCanvasTranslatePercent: 4,
  },
  "/assets/portraits/sienna-bae/portrait-flirty.png": {
    topTransparentPixels: 79,
    bottomTransparentPixels: 71,
    visibleHeightPixels: 1624,
    renderedVisibleHeightRatio: 0.9154,
    className: "translate-y-[4.00%]",
    renderedCanvasTranslatePercent: 4,
  },
  "/assets/portraits/sienna-bae/portrait.png": {
    topTransparentPixels: 88,
    bottomTransparentPixels: 78,
    visibleHeightPixels: 1608,
    renderedVisibleHeightRatio: 0.9064,
    className: "translate-y-[4.40%]",
    renderedCanvasTranslatePercent: 4.4,
  },
  "/assets/portraits/tasha-rell/portrait-angry.png": {
    topTransparentPixels: 60,
    bottomTransparentPixels: 98,
    visibleHeightPixels: 1666,
    renderedVisibleHeightRatio: 0.9134,
    className: "translate-y-[5.37%]",
    renderedCanvasTranslatePercent: 5.37,
  },
  "/assets/portraits/tasha-rell/portrait-confused.png": {
    topTransparentPixels: 55,
    bottomTransparentPixels: 48,
    visibleHeightPixels: 1728,
    renderedVisibleHeightRatio: 0.9437,
    className: "translate-y-[2.62%]",
    renderedCanvasTranslatePercent: 2.62,
  },
  "/assets/portraits/tasha-rell/portrait-flirty.png": {
    topTransparentPixels: 71,
    bottomTransparentPixels: 75,
    visibleHeightPixels: 1694,
    renderedVisibleHeightRatio: 0.9207,
    className: "translate-y-[4.08%]",
    renderedCanvasTranslatePercent: 4.08,
  },
  "/assets/portraits/tasha-rell/portrait.png": {
    topTransparentPixels: 60,
    bottomTransparentPixels: 37,
    visibleHeightPixels: 1725,
    renderedVisibleHeightRatio: 0.9468,
    className: "translate-y-[2.03%]",
    renderedCanvasTranslatePercent: 2.03,
  },
  "/assets/portraits/toby-wenz/portrait-angry.png": {
    topTransparentPixels: 65,
    bottomTransparentPixels: 52,
    visibleHeightPixels: 1657,
    renderedVisibleHeightRatio: 0.934,
    className: "translate-y-[2.93%]",
    renderedCanvasTranslatePercent: 2.93,
  },
  "/assets/portraits/toby-wenz/portrait-confused.png": {
    topTransparentPixels: 45,
    bottomTransparentPixels: 76,
    visibleHeightPixels: 1653,
    renderedVisibleHeightRatio: 0.9318,
    className: "translate-y-[4.28%]",
    renderedCanvasTranslatePercent: 4.28,
  },
  "/assets/portraits/toby-wenz/portrait-flirty.png": {
    topTransparentPixels: 48,
    bottomTransparentPixels: 86,
    visibleHeightPixels: 1640,
    renderedVisibleHeightRatio: 0.9245,
    className: "translate-y-[4.85%]",
    renderedCanvasTranslatePercent: 4.85,
  },
  "/assets/portraits/toby-wenz/portrait.png": {
    topTransparentPixels: 17,
    bottomTransparentPixels: 19,
    visibleHeightPixels: 1738,
    renderedVisibleHeightRatio: 0.9797,
    className: "translate-y-[1.07%]",
    renderedCanvasTranslatePercent: 1.07,
  },
  "/assets/portraits/venus/portrait-angry.png": {
    topTransparentPixels: 38,
    bottomTransparentPixels: 77,
    visibleHeightPixels: 1659,
    renderedVisibleHeightRatio: 0.9352,
    className: "translate-y-[4.34%]",
    renderedCanvasTranslatePercent: 4.34,
  },
  "/assets/portraits/venus/portrait-confused.png": {
    topTransparentPixels: 41,
    bottomTransparentPixels: 41,
    visibleHeightPixels: 1692,
    renderedVisibleHeightRatio: 0.9538,
    className: "translate-y-[2.31%]",
    renderedCanvasTranslatePercent: 2.31,
  },
  "/assets/portraits/venus/portrait-flirty.png": {
    topTransparentPixels: 38,
    bottomTransparentPixels: 19,
    visibleHeightPixels: 1717,
    renderedVisibleHeightRatio: 0.9679,
    className: "translate-y-[1.07%]",
    renderedCanvasTranslatePercent: 1.07,
  },
  "/assets/portraits/venus/portrait.png": {
    topTransparentPixels: 45,
    bottomTransparentPixels: 62,
    visibleHeightPixels: 1667,
    renderedVisibleHeightRatio: 0.9397,
    className: "translate-y-[3.49%]",
    renderedCanvasTranslatePercent: 3.49,
  },
  "/assets/portraits/vhool/portrait-angry.png": {
    topTransparentPixels: 10,
    bottomTransparentPixels: 5,
    visibleHeightPixels: 1759,
    renderedVisibleHeightRatio: 0.9915,
    className: "translate-y-[0.28%]",
    renderedCanvasTranslatePercent: 0.28,
  },
  "/assets/portraits/vhool/portrait-confused.png": {
    topTransparentPixels: 31,
    bottomTransparentPixels: 34,
    visibleHeightPixels: 1709,
    renderedVisibleHeightRatio: 0.9634,
    className: "translate-y-[1.92%]",
    renderedCanvasTranslatePercent: 1.92,
  },
  "/assets/portraits/vhool/portrait-flirty.png": {
    topTransparentPixels: 10,
    bottomTransparentPixels: 17,
    visibleHeightPixels: 1747,
    renderedVisibleHeightRatio: 0.9848,
    className: "translate-y-[0.96%]",
    renderedCanvasTranslatePercent: 0.96,
  },
  "/assets/portraits/vhool/portrait.png": {
    topTransparentPixels: 0,
    bottomTransparentPixels: 55,
    visibleHeightPixels: 1719,
    renderedVisibleHeightRatio: 0.969,
    className: "translate-y-[3.10%]",
    renderedCanvasTranslatePercent: 3.1,
  },
};
