#!/usr/bin/env node
// Member voice tuning rig.
//
// You (an agent) play the partner. The focus member is generated by the same
// AI prompt pipeline that runs in gameplay. Each turn is one CLI invocation,
// so you can read the result, edit the member fixture, and re-run with the
// same transcript loaded. Sessions persist as JSON under .claude-tmp/tune/.
//
// Run --help for the full usage.

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createServer, loadEnv } from "vite";

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const PROJECT_ROOT = resolve(dirname(SCRIPT_PATH), "..");
const TUNE_DIR = resolve(PROJECT_ROOT, ".claude-tmp/tune");
const ACTIVE_POINTER = resolve(TUNE_DIR, "active.txt");

const EXIT_OK = 0;
const EXIT_ERROR = 1;
const EXIT_BAD_ARGS = 2;
const SESSION_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$/;

loadDevelopmentEnv();

main().catch((error) => {
  console.error("tune failed:", error.stack ?? error.message ?? error);
  process.exit(EXIT_ERROR);
});

function loadDevelopmentEnv() {
  const loaded = loadEnv("development", PROJECT_ROOT, "");

  for (const [key, value] of Object.entries(loaded)) {
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

async function main() {
  const rawArgs = process.argv.slice(2);
  // `vp run tune -- foo` passes a literal `--` separator. Drop any leading `--`
  // tokens so the next token is treated as the subcommand.
  const args = [];
  let seenSeparator = false;
  for (const token of rawArgs) {
    if (!seenSeparator && token === "--") {
      seenSeparator = true;
      continue;
    }
    args.push(token);
  }

  if (args.length === 0 || args[0] === "--help" || args[0] === "-h" || args[0] === "help") {
    printHelp();
    process.exit(EXIT_OK);
  }

  const command = args[0];
  const rest = args.slice(1);

  switch (command) {
    case "members":
      await runListMembers();
      break;
    case "scenarios":
      await runListScenarios();
      break;
    case "sessions":
      runListSessions();
      break;
    case "use":
      runUseSession(rest);
      break;
    case "show":
      await runShow(rest);
      break;
    case "start":
      await runStart(rest);
      break;
    case "say":
      await runSay(rest);
      break;
    case "turn":
      await runTurn(rest);
      break;
    case "retry":
      await runRetry(rest);
      break;
    case "preview":
      await runPreview(rest);
      break;
    case "event":
      await runEvent(rest);
      break;
    case "nudge":
      await runNudge(rest);
      break;
    case "judge":
      await runJudge(rest);
      break;
    default:
      console.error(`Unknown command: ${command}. Run with --help.`);
      process.exit(EXIT_BAD_ARGS);
  }
}

async function withTuneModule(action) {
  ensureTuneDir();
  const server = await createServer({
    configFile: resolve(PROJECT_ROOT, "vite.config.ts"),
    root: PROJECT_ROOT,
    server: { middlewareMode: true, hmr: false, ws: false },
    appType: "custom",
    logLevel: "error",
  });
  try {
    const tune = await server.ssrLoadModule("/app/services/tune-member.ts");
    return await action(tune);
  } finally {
    await server.close();
  }
}

function ensureTuneDir() {
  if (!existsSync(TUNE_DIR)) {
    mkdirSync(TUNE_DIR, { recursive: true });
  }
}

function sessionPath(name) {
  const safeName = requireSessionName(name);
  const path = resolve(TUNE_DIR, `${safeName}.json`);
  assertPathInsideTuneDir(path);
  return path;
}

function requireSessionName(name) {
  if (typeof name !== "string" || name.length === 0) {
    throw new Error("Tune session name cannot be empty.");
  }
  if (!SESSION_NAME_PATTERN.test(name)) {
    throw new Error(
      "Tune session names may use letters, numbers, dots, underscores, and hyphens only.",
    );
  }
  return name;
}

function assertPathInsideTuneDir(path) {
  const relativePath = relative(TUNE_DIR, path);
  if (relativePath.startsWith("..") || isAbsolute(relativePath)) {
    throw new Error("Tune session path escaped the tune directory.");
  }
}

function loadSession(name) {
  const path = sessionPath(name);
  if (!existsSync(path)) {
    throw new Error(`No tune session named "${name}". Run \`tune sessions\` to list.`);
  }
  const text = readFileSync(path, "utf8");
  return JSON.parse(text);
}

function saveSession(name, session) {
  ensureTuneDir();
  writeFileSync(sessionPath(name), `${JSON.stringify(session, null, 2)}\n`, "utf8");
}

function setActiveSessionName(name) {
  ensureTuneDir();
  writeFileSync(ACTIVE_POINTER, `${requireSessionName(name)}\n`, "utf8");
}

function readActiveSessionName() {
  if (!existsSync(ACTIVE_POINTER)) {
    return null;
  }
  return readFileSync(ACTIVE_POINTER, "utf8").trim() || null;
}

function requireActiveSessionName() {
  const name = readActiveSessionName();
  if (name === null) {
    throw new Error("No active tune session. Run `tune start <member>` first.");
  }
  return name;
}

async function runListMembers() {
  await withTuneModule((tune) => {
    const members = tune.listAvailableMembers();
    for (const member of members) {
      process.stdout.write(`${member.id}\t${member.name}\n`);
    }
  });
}

async function runListScenarios() {
  await withTuneModule((tune) => {
    const scenarios = tune.listAvailableScenarios();
    for (const scenario of scenarios) {
      process.stdout.write(`${scenario.id}\t${scenario.title}\n`);
    }
  });
}

function runListSessions() {
  ensureTuneDir();
  const active = readActiveSessionName();
  const entries = readdirSync(TUNE_DIR)
    .filter((file) => file.endsWith(".json"))
    .map((file) => file.replace(/\.json$/, ""))
    .sort();
  if (entries.length === 0) {
    process.stdout.write("(no tune sessions)\n");
    return;
  }
  for (const name of entries) {
    const marker = name === active ? "* " : "  ";
    let summary;
    try {
      const session = loadSession(name);
      summary = `${session.focusMemberId} vs ${session.partnerMemberId} @ ${session.scenarioId} (${session.messages.length} messages)`;
    } catch {
      summary = "(unreadable)";
    }
    process.stdout.write(`${marker}${name}\t${summary}\n`);
  }
}

function runUseSession(args) {
  const name = args[0];
  if (typeof name !== "string" || name.length === 0) {
    throw new Error("Usage: tune use <session-name>");
  }
  if (!existsSync(sessionPath(name))) {
    throw new Error(`No tune session named "${name}".`);
  }
  setActiveSessionName(name);
  process.stdout.write(`Active session: ${name}\n`);
}

async function runStart(args) {
  const parsed = parseStartArgs(args);
  await withTuneModule(async (tune) => {
    const session = tune.createTuneSession({
      focusMemberId: parsed.focusMemberId,
      partnerMemberId: parsed.partnerMemberId,
      scenarioId: parsed.scenarioId,
      openerSide: parsed.focusOpens ? "focus" : "partner",
    });
    const name = parsed.name ?? defaultSessionName(parsed.focusMemberId);
    saveSession(name, session);
    setActiveSessionName(name);

    const focus = tune.findMemberById(session.focusMemberId);
    const partner = tune.findMemberById(session.partnerMemberId);
    const scenario = tune.findScenarioById(session.scenarioId);

    process.stdout.write(
      [
        `Session "${name}" started.`,
        `  Focus:    ${focus.name} (${focus.id})`,
        `  Partner:  ${partner.name} (${partner.id})   <- you play this side`,
        `  Scenario: ${scenario.title} (${scenario.id})`,
        `  Opens:    ${session.openerSide}`,
        "",
        session.openerSide === "partner"
          ? `Next: \`tune say "<your opener>"\` to begin.`
          : `Next: \`tune turn\` to make ${focus.firstName} open.`,
      ].join("\n") + "\n",
    );
  });
}

function defaultSessionName(focusMemberId) {
  const iso = new Date().toISOString();
  const date = iso.slice(0, 10);
  const hhmm = iso.slice(11, 16).replace(":", "");
  return `${focusMemberId}-${date}-${hhmm}`;
}

function parseStartArgs(args) {
  if (args.length === 0) {
    throw new Error(
      "Usage: tune start <focusMemberId> [--partner <id>] [--scenario <id>] [--name <name>] [--focus-opens]",
    );
  }
  if (args[0].startsWith("--")) {
    throw new Error("Usage: tune start <focusMemberId> [options]");
  }
  const result = {
    focusMemberId: args[0],
    partnerMemberId: undefined,
    scenarioId: undefined,
    name: undefined,
    focusOpens: false,
  };
  for (let index = 1; index < args.length; index += 1) {
    const token = args[index];
    switch (token) {
      case "--partner":
        result.partnerMemberId = requireFlagValue(args, index);
        index += 1;
        break;
      case "--scenario":
        result.scenarioId = requireFlagValue(args, index);
        index += 1;
        break;
      case "--name":
        result.name = requireSessionName(requireFlagValue(args, index));
        index += 1;
        break;
      case "--focus-opens":
        result.focusOpens = true;
        break;
      default:
        throw new Error(`Unknown start flag: ${token}`);
    }
  }
  return result;
}

async function runSay(args) {
  const parsed = parseSayArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule(async (tune) => {
    const withPartner = tune.appendPartnerLine(session, parsed.text);
    saveSession(name, withPartner);
    if (parsed.noReply) {
      process.stdout.write(formatPartnerEcho(withPartner, tune));
      return;
    }
    await generateAndPrint(name, withPartner, tune, parsed);
  });
}

function parseSayArgs(args) {
  if (args.length === 0) {
    throw new Error(
      'Usage: tune say "<text>" [--no-reply] [--show-prompt] [--session <name>] [ai options]',
    );
  }
  const result = {
    text: args[0],
    noReply: false,
    showPrompt: false,
    showSystem: false,
    session: undefined,
    config: {},
  };
  for (let index = 1; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--no-reply") {
      result.noReply = true;
    } else if (token === "--show-prompt") {
      result.showPrompt = true;
    } else if (token === "--show-system") {
      result.showSystem = true;
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else if (isRuntimeConfigFlag(token)) {
      index = readRuntimeConfigFlag(args, index, result.config);
    } else {
      throw new Error(`Unknown say flag: ${token}`);
    }
  }
  return result;
}

async function runTurn(args) {
  const parsed = parseTurnArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule(async (tune) => {
    await generateAndPrint(name, session, tune, parsed);
  });
}

function parseTurnArgs(args) {
  const result = { showPrompt: false, showSystem: false, session: undefined, config: {} };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--show-prompt") {
      result.showPrompt = true;
    } else if (token === "--show-system") {
      result.showSystem = true;
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else if (isRuntimeConfigFlag(token)) {
      index = readRuntimeConfigFlag(args, index, result.config);
    } else {
      throw new Error(`Unknown turn flag: ${token}`);
    }
  }
  return result;
}

async function runRetry(args) {
  const parsed = parseTurnArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule(async (tune) => {
    const withoutLastReply = tune.dropLastFocusMemberReply(session);
    saveSession(name, withoutLastReply);
    await generateAndPrint(name, withoutLastReply, tune, parsed);
  });
}

async function runEvent(args) {
  const parsed = parseEventArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule((tune) => {
    const next = tune.appendDirectorEvent(session, parsed.text);
    saveSession(name, next);
    process.stdout.write(`[event recorded on ${name}] ${parsed.text}\n`);
  });
}

function parseEventArgs(args) {
  if (args.length === 0 || typeof args[0] !== "string" || args[0].length === 0) {
    throw new Error('Usage: tune event "<text>" [--session <name>]');
  }
  const result = { text: args[0], session: undefined };
  for (let index = 1; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else {
      throw new Error(`Unknown event flag: ${token}`);
    }
  }
  return result;
}

async function runNudge(args) {
  const parsed = parseNudgeArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule((tune) => {
    const next = tune.appendCupidNote(session, parsed.text);
    saveSession(name, next);
    process.stdout.write(`[cupid note recorded on ${name}] ${parsed.text}\n`);
  });
}

function parseNudgeArgs(args) {
  if (args.length === 0 || typeof args[0] !== "string" || args[0].length === 0) {
    throw new Error('Usage: tune nudge "<text>" [--session <name>]');
  }
  const result = { text: args[0], session: undefined };
  for (let index = 1; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else {
      throw new Error(`Unknown nudge flag: ${token}`);
    }
  }
  return result;
}

async function runJudge(args) {
  const parsed = parseJudgeArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule((tune) => {
    const next = tune.appendJudgeSnapshot(session, {
      dateHealthDelta: parsed.dateHealthDelta,
      note: parsed.note,
    });
    saveSession(name, next);
    const sign =
      parsed.dateHealthDelta >= 0 ? `+${parsed.dateHealthDelta}` : `${parsed.dateHealthDelta}`;
    process.stdout.write(
      `[judge snapshot recorded on ${name}] ${sign} health: ${parsed.note ?? "Manual judge snapshot."}\n`,
    );
  });
}

function parseJudgeArgs(args) {
  if (args.length === 0) {
    throw new Error(
      'Usage: tune judge <dateHealthDelta> [--note "<text>"] [--session <name>]. Delta is an integer in [-50, 50]. Negative values cool the date.',
    );
  }
  const result = { dateHealthDelta: undefined, note: undefined, session: undefined };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--note") {
      result.note = requireFlagValue(args, index);
      index += 1;
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else if (result.dateHealthDelta === undefined) {
      const parsed = Number(token);
      if (!Number.isFinite(parsed) || !Number.isInteger(parsed)) {
        throw new Error(`Judge delta must be an integer, got "${token}".`);
      }
      result.dateHealthDelta = parsed;
    } else {
      throw new Error(`Unknown judge flag: ${token}`);
    }
  }
  if (result.dateHealthDelta === undefined) {
    throw new Error("Judge command requires a dateHealthDelta integer as the first argument.");
  }
  return result;
}

async function runPreview(args) {
  const parsed = parsePreviewArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule((tune) => {
    const preview = tune.previewMemberTurnPacket(session);
    if (parsed.section === "system") {
      process.stdout.write(`${preview.packet.system}\n`);
    } else if (parsed.section === "thread") {
      const lines = preview.packet.messages.map((message) => {
        const content =
          typeof message.content === "string"
            ? message.content
            : message.content
                .map((part) => (part.type === "text" ? part.text : `[${part.type}]`))
                .join(" ");
        return `[${message.role}] ${content}`;
      });
      process.stdout.write(`${lines.join("\n\n")}\n`);
    } else {
      process.stdout.write(`${preview.packet.prompt}\n`);
    }
  });
}

function parsePreviewArgs(args) {
  const result = { section: "prompt", session: undefined };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--system") {
      result.section = "system";
    } else if (token === "--thread") {
      result.section = "thread";
    } else if (token === "--prompt") {
      result.section = "prompt";
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else {
      throw new Error(`Unknown preview flag: ${token}`);
    }
  }
  return result;
}

async function runShow(args) {
  const parsed = parseShowArgs(args);
  const name = parsed.name ?? requireActiveSessionName();
  const session = loadSession(name);

  await withTuneModule((tune) => {
    const focus = tune.findMemberById(session.focusMemberId);
    const partner = tune.findMemberById(session.partnerMemberId);
    const scenario = tune.findScenarioById(session.scenarioId);

    const header = [
      `Session: ${name}`,
      `  Focus:    ${focus.name} (${focus.id})`,
      `  Partner:  ${partner.name} (${partner.id})`,
      `  Scenario: ${scenario.title} (${scenario.id})`,
      `  Messages: ${session.messages.length}`,
    ].join("\n");

    process.stdout.write(`${header}\n\n`);

    if (parsed.showPrompt) {
      if (typeof session.lastPromptSystem !== "string") {
        process.stdout.write("(no prompt recorded yet, run `tune turn` or `tune say` first)\n");
      } else {
        process.stdout.write(`--- last system prompt ---\n${session.lastPromptSystem}\n`);
      }
      return;
    }

    const transcript = tune.formatTranscriptForReading(session, {
      focusName: focus.firstName,
      partnerName: partner.firstName,
    });
    process.stdout.write(`${transcript}\n`);
  });
}

function parseShowArgs(args) {
  const result = { name: undefined, showPrompt: false };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--prompt") {
      result.showPrompt = true;
    } else if (token === "--name" || token === "--session") {
      result.name = requireFlagValue(args, index);
      index += 1;
    } else {
      throw new Error(`Unknown show flag: ${token}`);
    }
  }
  return result;
}

async function generateAndPrint(name, sessionBeforeReply, tune, options) {
  const focus = tune.findMemberById(sessionBeforeReply.focusMemberId);
  const result = await tune.generateFocusMemberReply(sessionBeforeReply, {
    config: resolveRuntimeConfig(options.config ?? {}),
  });
  saveSession(name, result.session);

  if (options.showSystem) {
    process.stdout.write(
      `--- system prompt ---\n${result.preview.packet.system}\n--- end system prompt ---\n\n`,
    );
  } else if (options.showPrompt) {
    process.stdout.write(
      `--- full prompt ---\n${result.preview.packet.prompt}\n--- end prompt ---\n\n`,
    );
  }

  process.stdout.write(`${focus.firstName}: ${result.replyText}\n`);

  const stats = [
    `model: ${result.modelId} (${result.providerMode})`,
    `tokens approx: ${result.approximatePromptTokens}`,
    result.retried ? `retried: ${result.retryReason}` : null,
  ]
    .filter((part) => part !== null)
    .join(" | ");
  process.stdout.write(`(${stats})\n`);

  for (const warning of result.warningMessages) {
    process.stdout.write(`note: ${warning}\n`);
  }
}

function isRuntimeConfigFlag(token) {
  return [
    "--provider",
    "--chat-model",
    "--gateway-key",
    "--gateway-base-url",
    "--reasoning",
    "--timeout-ms",
  ].includes(token);
}

function readRuntimeConfigFlag(args, index, config) {
  const token = args[index];
  const value = requireFlagValue(args, index);

  switch (token) {
    case "--provider":
      config.aiProvider = value;
      break;
    case "--chat-model":
      config.chatModel = value;
      break;
    case "--gateway-key":
      config.gatewayApiKey = value;
      break;
    case "--gateway-base-url":
      config.gatewayBaseURL = value;
      break;
    case "--reasoning":
      config.reasoningLevel = value;
      break;
    case "--timeout-ms": {
      const parsed = Number(value);
      if (!Number.isInteger(parsed) || parsed <= 0) {
        throw new Error("--timeout-ms must be a positive integer.");
      }
      config.requestTimeoutMs = parsed;
      break;
    }
    default:
      throw new Error(`Unknown AI option: ${token}`);
  }

  return index + 1;
}

function resolveRuntimeConfig(overrides) {
  const config = {};
  const provider = normalizeOptionalValue(overrides.aiProvider ?? process.env.TUNE_PROVIDER);
  const chatModel = normalizeOptionalValue(overrides.chatModel ?? process.env.TUNE_CHAT_MODEL);
  const gatewayApiKey = normalizeOptionalValue(
    overrides.gatewayApiKey ?? process.env.AI_GATEWAY_API_KEY,
  );
  const gatewayBaseURL = normalizeOptionalValue(
    overrides.gatewayBaseURL ?? process.env.AI_GATEWAY_BASE_URL,
  );
  const reasoningLevel = normalizeOptionalValue(
    overrides.reasoningLevel ?? process.env.TUNE_REASONING_LEVEL,
  );
  const timeoutMsRaw = overrides.requestTimeoutMs ?? process.env.TUNE_TIMEOUT_MS;

  if (provider !== undefined) {
    if (provider !== "ollama" && provider !== "gateway") {
      throw new Error("--provider must be ollama or gateway.");
    }
    config.aiProvider = provider;
  }
  if (chatModel !== undefined) config.chatModel = chatModel;
  if (gatewayApiKey !== undefined) config.gatewayApiKey = gatewayApiKey;
  if (gatewayBaseURL !== undefined) config.gatewayBaseURL = gatewayBaseURL;
  if (reasoningLevel !== undefined) config.reasoningLevel = reasoningLevel;

  if (timeoutMsRaw !== undefined) {
    const parsed = typeof timeoutMsRaw === "number" ? timeoutMsRaw : Number(timeoutMsRaw);
    if (!Number.isInteger(parsed) || parsed <= 0) {
      throw new Error("TUNE_TIMEOUT_MS must be a positive integer.");
    }
    config.requestTimeoutMs = parsed;
  }

  if (config.aiProvider === undefined && config.gatewayApiKey !== undefined) {
    config.aiProvider = "gateway";
  }

  return config;
}

function normalizeOptionalValue(value) {
  if (typeof value !== "string") {
    return value;
  }
  const trimmed = value.trim();
  return trimmed.length === 0 ? undefined : trimmed;
}

function requireFlagValue(args, index) {
  const value = args[index + 1];
  if (typeof value !== "string" || value.length === 0 || value.startsWith("--")) {
    throw new Error(`${args[index]} requires a value.`);
  }
  return value;
}

function formatPartnerEcho(session, tune) {
  const partner = tune.findMemberById(session.partnerMemberId);
  const lastMessage = session.messages[session.messages.length - 1];
  if (lastMessage === undefined || lastMessage.kind !== "character") {
    return "(partner line recorded)\n";
  }
  return `${partner.firstName} (you): ${lastMessage.text}\n`;
}

function printHelp() {
  process.stdout.write(
    [
      "Member voice tuning rig.",
      "",
      "You play the partner. The focus member is AI-generated against the same",
      "prompt pipeline gameplay uses. Sessions live under .claude-tmp/tune/.",
      "",
      "Usage:",
      "  node scripts/tune-member.mjs <command> [args]",
      "  vp run tune -- <command> [args]",
      "",
      "Commands:",
      "  start <focusId> [--partner <id>] [--scenario <id>] [--name <n>] [--focus-opens]",
      "      Initialize a new tune session and make it active.",
      "      Defaults: partner=alex-yoon, scenario=diner-eleven-pm, opener=partner.",
      "",
      `  say "<text>" [--no-reply] [--show-prompt] [--show-system] [--session <name>] [ai options]`,
      "      Record a partner line (you) and generate the focus member's reply.",
      "",
      "  turn [--show-prompt] [--show-system] [--session <name>] [ai options]",
      "      Generate the focus member's next turn without adding a partner line.",
      "      Useful when --focus-opens or after `event`/`nudge`.",
      "",
      "  retry [--show-prompt] [--show-system] [--session <name>] [ai options]",
      "      Drop the latest focus reply and generate it again from the prior transcript.",
      "      Use this after editing the focus member fixture.",
      "",
      "  preview [--system | --thread | --prompt] [--session <name>]",
      "      Build the next member turn's packet and print it without calling the AI.",
      "      Useful for inspecting what the model would see after fixture edits.",
      "",
      `  event "<text>" [--session <name>]`,
      "      Insert a scenario beat the focus member will see in-thread.",
      "",
      `  nudge "<text>" [--session <name>]`,
      "      Add a private Cupid coaching note targeting the focus member.",
      "",
      `  judge <delta> [--note "<text>"] [--session <name>]`,
      "      Insert a manual judge snapshot. Delta is an integer in [-50, 50]; negative cools the date,",
      "      positive warms it. The snapshot feeds dateHealth and pair-trajectory derivation, so it",
      "      shifts the focus member's sample weighting on the next turn.",
      "",
      "  show [--prompt] [--name <n> | --session <n>]",
      "      Print the active transcript, or with --prompt the last system prompt.",
      "",
      "  sessions",
      "      List all sessions on disk. The active one is marked with `*`.",
      "",
      "  use <name>",
      "      Make a session active for subsequent commands.",
      "",
      "  members",
      "      Print available member ids and names.",
      "",
      "  scenarios",
      "      Print available scenario ids and titles.",
      "",
      "AI options for say, turn, and retry:",
      "  --provider <name>       ollama | gateway",
      "  --chat-model <id>       Override chat model",
      "  --gateway-key <key>     Vercel AI Gateway key",
      "  --gateway-base-url <u>  Override Gateway base URL",
      "  --reasoning <level>     off | none | minimal | low | medium | high | xhigh",
      "  --timeout-ms <ms>       Request timeout",
      "",
      "Environment:",
      "  Loaded from shell env and git-ignored .env.local at the repo root.",
      "  TUNE_PROVIDER           ollama | gateway",
      "  TUNE_CHAT_MODEL         Chat model id",
      "  TUNE_REASONING_LEVEL    Reasoning level",
      "  TUNE_TIMEOUT_MS         Request timeout",
      "  AI_GATEWAY_API_KEY      Gateway key. If set, tune defaults to gateway.",
      "  AI_GATEWAY_BASE_URL     Gateway base URL",
      "",
      "Typical loop:",
      "  printf 'AI_GATEWAY_API_KEY=<key>\\n' > .env.local",
      "  vp run tune -- start cassie-conners --partner alex-yoon",
      `  vp run tune -- say "hey, you actually showed up"`,
      "  # read response, edit app/fixtures/members/cassie-conners.ts",
      "  vp run tune -- retry   # re-run the last focus reply with the updated fixture",
      "",
      "Parallel sessions:",
      "  `start` sets a single active session pointer (.claude-tmp/tune/active.txt). When running two",
      "  tune sessions side by side (e.g. two partner-play subagents), pass --session <name> on every",
      "  command after start (say/turn/retry/event/nudge/judge/preview/show) so each caller targets its",
      "  own session and never touches the shared pointer. Omitting --session falls back to the active",
      "  pointer, which is last-write-wins across parallel starts.",
      "",
    ].join("\n"),
  );
}
