#!/usr/bin/env node
// Member voice tuning rig.
//
// You (an agent) play the partner. The focus member is generated by the same
// AI prompt pipeline that runs in gameplay. Each turn is one CLI invocation,
// so you can read the result, edit the member fixture, and re-run with the
// same transcript loaded. Sessions persist as JSON under .claude-tmp/tune/.
//
// Run --help for the full usage.

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { createServer, loadEnv } from "vite";

import { printTuneMemberHelp } from "./tune-member-help.mjs";

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const PROJECT_ROOT = resolve(dirname(SCRIPT_PATH), "..");
const TUNE_DIR = resolve(PROJECT_ROOT, ".claude-tmp/tune");
const ACTIVE_POINTER = resolve(TUNE_DIR, "active.txt");

const EXIT_OK = 0;
const EXIT_ERROR = 1;
const EXIT_BAD_ARGS = 2;
const SESSION_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$/;
const DEFAULT_TUNE_GATEWAY_CHAT_MODEL = "deepseek/deepseek-v4-flash";
const DEEPSEEK_V4_PRO_MODEL = "deepseek/deepseek-v4-pro";
const DEFAULT_TUNE_DEEPSEEK_REASONING_LEVEL = "xhigh";

loadDevelopmentEnv();

main().catch((error) => {
  console.error("tune failed:", error.stack ?? error.message ?? error);
  process.exit(EXIT_ERROR);
});

function loadDevelopmentEnv() {
  const loaded = loadEnv("development", PROJECT_ROOT, "");

  for (const [key, value] of Object.entries(loaded)) {
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

async function main() {
  const rawArgs = process.argv.slice(2);
  // `vp run tune -- foo` passes a literal `--` separator. Drop any leading `--`
  // tokens so the next token is treated as the subcommand.
  const args = [];
  let seenSeparator = false;
  for (const token of rawArgs) {
    if (!seenSeparator && token === "--") {
      seenSeparator = true;
      continue;
    }
    args.push(token);
  }

  if (args.length === 0 || args[0] === "--help" || args[0] === "-h" || args[0] === "help") {
    printTuneMemberHelp();
    process.exit(EXIT_OK);
  }

  const command = args[0];
  const rest = args.slice(1);

  switch (command) {
    case "members":
      await runListMembers();
      break;
    case "scenarios":
      await runListScenarios();
      break;
    case "sessions":
      runListSessions();
      break;
    case "use":
      runUseSession(rest);
      break;
    case "show":
      await runShow(rest);
      break;
    case "start":
      await runStart(rest);
      break;
    case "say":
      await runSay(rest);
      break;
    case "turn":
      await runTurn(rest);
      break;
    case "auto":
      await runAuto(rest);
      break;
    case "retry":
      await runRetry(rest);
      break;
    case "preview":
      await runPreview(rest);
      break;
    case "event":
      await runEvent(rest);
      break;
    case "nudge":
      await runNudge(rest);
      break;
    case "judge":
      await runJudge(rest);
      break;
    default:
      console.error(`Unknown command: ${command}. Run with --help.`);
      process.exit(EXIT_BAD_ARGS);
  }
}

async function withTuneModule(action) {
  ensureTuneDir();
  const server = await createServer({
    configFile: resolve(PROJECT_ROOT, "vite.config.ts"),
    root: PROJECT_ROOT,
    server: { middlewareMode: true, hmr: false, ws: false },
    appType: "custom",
    logLevel: "error",
  });
  try {
    const tune = await server.ssrLoadModule("/app/services/tune-member.ts");
    return await action(tune);
  } finally {
    await server.close();
  }
}

function ensureTuneDir() {
  if (!existsSync(TUNE_DIR)) {
    mkdirSync(TUNE_DIR, { recursive: true });
  }
}

function sessionPath(name) {
  const safeName = requireSessionName(name);
  const path = resolve(TUNE_DIR, `${safeName}.json`);
  assertPathInsideTuneDir(path);
  return path;
}

function requireSessionName(name) {
  if (typeof name !== "string" || name.length === 0) {
    throw new Error("Tune session name cannot be empty.");
  }
  if (!SESSION_NAME_PATTERN.test(name)) {
    throw new Error(
      "Tune session names may use letters, numbers, dots, underscores, and hyphens only.",
    );
  }
  return name;
}

function assertPathInsideTuneDir(path) {
  const relativePath = relative(TUNE_DIR, path);
  if (relativePath.startsWith("..") || isAbsolute(relativePath)) {
    throw new Error("Tune session path escaped the tune directory.");
  }
}

function loadSession(name) {
  const path = sessionPath(name);
  if (!existsSync(path)) {
    throw new Error(`No tune session named "${name}". Run \`tune sessions\` to list.`);
  }
  const text = readFileSync(path, "utf8");
  return JSON.parse(text);
}

function saveSession(name, session) {
  ensureTuneDir();
  writeFileSync(sessionPath(name), `${JSON.stringify(session, null, 2)}\n`, "utf8");
}

function setActiveSessionName(name) {
  ensureTuneDir();
  writeFileSync(ACTIVE_POINTER, `${requireSessionName(name)}\n`, "utf8");
}

function readActiveSessionName() {
  if (!existsSync(ACTIVE_POINTER)) {
    return null;
  }
  return readFileSync(ACTIVE_POINTER, "utf8").trim() || null;
}

function requireActiveSessionName() {
  const name = readActiveSessionName();
  if (name === null) {
    throw new Error("No active tune session. Run `tune start <member>` first.");
  }
  return name;
}

function partnerControlOf(session) {
  return session.partnerControl ?? "manual";
}

async function runListMembers() {
  await withTuneModule((tune) => {
    const members = tune.listAvailableMembers();
    for (const member of members) {
      process.stdout.write(`${member.id}\t${member.name}\n`);
    }
  });
}

async function runListScenarios() {
  await withTuneModule((tune) => {
    const scenarios = tune.listAvailableScenarios();
    for (const scenario of scenarios) {
      process.stdout.write(`${scenario.id}\t${scenario.title}\n`);
    }
  });
}

function runListSessions() {
  ensureTuneDir();
  const active = readActiveSessionName();
  const entries = readdirSync(TUNE_DIR)
    .filter((file) => file.endsWith(".json"))
    .map((file) => file.replace(/\.json$/, ""))
    .sort();
  if (entries.length === 0) {
    process.stdout.write("(no tune sessions)\n");
    return;
  }
  for (const name of entries) {
    const marker = name === active ? "* " : "  ";
    let summary;
    try {
      const session = loadSession(name);
      summary = `${session.focusMemberId} vs ${session.partnerMemberId} @ ${session.scenarioId} (${session.messages.length} messages)`;
    } catch {
      summary = "(unreadable)";
    }
    process.stdout.write(`${marker}${name}\t${summary}\n`);
  }
}

function runUseSession(args) {
  const name = args[0];
  if (typeof name !== "string" || name.length === 0) {
    throw new Error("Usage: tune use <session-name>");
  }
  if (!existsSync(sessionPath(name))) {
    throw new Error(`No tune session named "${name}".`);
  }
  setActiveSessionName(name);
  process.stdout.write(`Active session: ${name}\n`);
}

async function runStart(args) {
  const parsed = parseStartArgs(args);
  await withTuneModule(async (tune) => {
    const session = tune.createTuneSession({
      focusMemberId: parsed.focusMemberId,
      partnerMemberId: parsed.partnerMemberId,
      scenarioId: parsed.scenarioId,
      openerSide: parsed.focusOpens ? "focus" : "partner",
      partnerControl: parsed.partnerControl,
      focusRequestId: parsed.focusRequestId,
    });
    const name = parsed.name ?? defaultSessionName(parsed.focusMemberId);
    saveSession(name, session);
    setActiveSessionName(name);

    const focus = tune.findMemberById(session.focusMemberId);
    const partner = tune.findMemberById(session.partnerMemberId);
    const scenario = tune.findScenarioById(session.scenarioId);
    const focusRequest =
      session.focusRequestId === undefined
        ? undefined
        : tune.findMemberRequestById(session.focusRequestId);

    process.stdout.write(
      [
        `Session "${name}" started.`,
        `  Focus:    ${focus.name} (${focus.id})`,
        partnerControlOf(session) === "ai"
          ? `  Partner:  ${partner.name} (${partner.id})   <- AI-generated in auto mode`
          : `  Partner:  ${partner.name} (${partner.id})   <- you play this side`,
        `  Scenario: ${scenario.title} (${scenario.id})`,
        `  Mode:     ${partnerControlOf(session) === "ai" ? "AI controls both members" : "manual partner control"}`,
        `  Opens:    ${session.openerSide}`,
        focusRequest === undefined
          ? `  Request:  (none — pass --focus-request <id> to inject a <focus> block)`
          : `  Request:  ${focusRequest.id} — ${focusRequest.text}`,
        "",
        partnerControlOf(session) === "ai"
          ? `Next: \`tune auto --turns 2\` to run live-like AI turns.`
          : session.openerSide === "partner"
            ? `Next: \`tune say "<your opener>"\` to begin.`
            : `Next: \`tune turn\` to make ${focus.firstName} open.`,
      ].join("\n") + "\n",
    );
  });
}

function defaultSessionName(focusMemberId) {
  const iso = new Date().toISOString();
  const date = iso.slice(0, 10);
  const hhmm = iso.slice(11, 16).replace(":", "");
  return `${focusMemberId}-${date}-${hhmm}`;
}

function parseStartArgs(args) {
  if (args.length === 0) {
    throw new Error(
      "Usage: tune start <focusMemberId> [--partner <id>] [--scenario <id>] [--name <name>] [--focus-opens] [--ai-partner] [--focus-request <id>]",
    );
  }
  if (args[0].startsWith("--")) {
    throw new Error("Usage: tune start <focusMemberId> [options]");
  }
  const result = {
    focusMemberId: args[0],
    partnerMemberId: undefined,
    scenarioId: undefined,
    name: undefined,
    focusOpens: false,
    partnerControl: "manual",
    focusRequestId: undefined,
  };
  for (let index = 1; index < args.length; index += 1) {
    const token = args[index];
    switch (token) {
      case "--partner":
        result.partnerMemberId = requireFlagValue(args, index);
        index += 1;
        break;
      case "--scenario":
        result.scenarioId = requireFlagValue(args, index);
        index += 1;
        break;
      case "--name":
        result.name = requireSessionName(requireFlagValue(args, index));
        index += 1;
        break;
      case "--focus-opens":
        result.focusOpens = true;
        break;
      case "--ai-partner":
        result.partnerControl = "ai";
        break;
      case "--manual-partner":
        result.partnerControl = "manual";
        break;
      case "--focus-request":
        result.focusRequestId = requireFlagValue(args, index);
        index += 1;
        break;
      default:
        throw new Error(`Unknown start flag: ${token}`);
    }
  }
  return result;
}

async function runAuto(args) {
  const parsed = parseAutoArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  let session = loadSession(name);
  if (partnerControlOf(session) !== "ai") {
    throw new Error(
      "`tune auto` is only meaningful in AI partner sessions. Start with `tune start --ai-partner`.",
    );
  }
  await withTuneModule(async (tune) => {
    for (let index = 0; index < parsed.turns; index += 1) {
      const result = await tune.generateMemberReply(session, {
        config: resolveRuntimeConfig(parsed.config),
        generationOptions: resolveGenerationOptions(parsed.generationOptions),
        speakerRole: tune.nextLiveSpeakerRole(session),
      });
      session = result.session;
      saveSession(name, session);
      printGenerationResult(result, parsed);
    }
  });
}

function parseAutoArgs(args) {
  const result = {
    turns: 1,
    showPrompt: false,
    showSystem: false,
    session: undefined,
    config: {},
    generationOptions: {},
  };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--turns") {
      const value = requireFlagValue(args, index);
      const parsed = Number(value);
      if (!Number.isInteger(parsed) || parsed <= 0 || parsed > 24) {
        throw new Error("--turns must be an integer from 1 to 24.");
      }
      result.turns = parsed;
      index += 1;
    } else if (token === "--show-prompt") {
      result.showPrompt = true;
    } else if (token === "--show-system") {
      result.showSystem = true;
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else if (isGenerationOptionFlag(token)) {
      readGenerationOptionFlag(token, result.generationOptions);
    } else if (isRuntimeConfigFlag(token)) {
      index = readRuntimeConfigFlag(args, index, result.config);
    } else {
      throw new Error(`Unknown auto flag: ${token}`);
    }
  }
  return result;
}

async function runSay(args) {
  const parsed = parseSayArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  if (partnerControlOf(session) === "ai") {
    throw new Error(
      "`tune say` is only meaningful in manual partner sessions. Use `tune auto` to drive the AI partner instead.",
    );
  }
  await withTuneModule(async (tune) => {
    const withPartner = tune.appendPartnerLine(session, parsed.text);
    saveSession(name, withPartner);
    if (parsed.noReply) {
      process.stdout.write(formatPartnerEcho(withPartner, tune));
      return;
    }
    await generateAndPrint(name, withPartner, tune, parsed);
  });
}

function parseSayArgs(args) {
  if (args.length === 0) {
    throw new Error(
      'Usage: tune say "<text>" [--no-reply] [--show-prompt] [--session <name>] [ai options]',
    );
  }
  const result = {
    text: args[0],
    noReply: false,
    showPrompt: false,
    showSystem: false,
    session: undefined,
    config: {},
    generationOptions: {},
  };
  for (let index = 1; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--no-reply") {
      result.noReply = true;
    } else if (token === "--show-prompt") {
      result.showPrompt = true;
    } else if (token === "--show-system") {
      result.showSystem = true;
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else if (isGenerationOptionFlag(token)) {
      readGenerationOptionFlag(token, result.generationOptions);
    } else if (isRuntimeConfigFlag(token)) {
      index = readRuntimeConfigFlag(args, index, result.config);
    } else {
      throw new Error(`Unknown say flag: ${token}`);
    }
  }
  return result;
}

async function runTurn(args) {
  const parsed = parseTurnArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  if (partnerControlOf(session) === "ai") {
    throw new Error(
      "`tune turn` forces a focus reply; in AI partner sessions use `tune auto` instead.",
    );
  }
  await withTuneModule(async (tune) => {
    await generateAndPrint(name, session, tune, parsed);
  });
}

function parseTurnArgs(args) {
  const result = {
    showPrompt: false,
    showSystem: false,
    session: undefined,
    config: {},
    generationOptions: {},
  };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--show-prompt") {
      result.showPrompt = true;
    } else if (token === "--show-system") {
      result.showSystem = true;
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else if (isGenerationOptionFlag(token)) {
      readGenerationOptionFlag(token, result.generationOptions);
    } else if (isRuntimeConfigFlag(token)) {
      index = readRuntimeConfigFlag(args, index, result.config);
    } else {
      throw new Error(`Unknown turn flag: ${token}`);
    }
  }
  return result;
}

async function runRetry(args) {
  const parsed = parseTurnArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule(async (tune) => {
    const withoutLastReply = tune.dropLastReply(session);
    const speakerRole =
      partnerControlOf(withoutLastReply) === "ai"
        ? tune.nextLiveSpeakerRole(withoutLastReply)
        : "focus";
    const result = await tune.generateMemberReply(withoutLastReply, {
      config: resolveRuntimeConfig(parsed.config),
      generationOptions: resolveGenerationOptions(parsed.generationOptions),
      speakerRole,
    });
    saveSession(name, result.session);
    printGenerationResult(result, parsed);
  });
}

async function runEvent(args) {
  const parsed = parseEventArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule((tune) => {
    const next = tune.appendDirectorEvent(session, parsed.text);
    saveSession(name, next);
    process.stdout.write(`[event recorded on ${name}] ${parsed.text}\n`);
  });
}

function parseEventArgs(args) {
  if (args.length === 0 || typeof args[0] !== "string" || args[0].length === 0) {
    throw new Error('Usage: tune event "<text>" [--session <name>]');
  }
  const result = { text: args[0], session: undefined };
  for (let index = 1; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else {
      throw new Error(`Unknown event flag: ${token}`);
    }
  }
  return result;
}

async function runNudge(args) {
  const parsed = parseNudgeArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule((tune) => {
    const next = tune.appendCupidNote(session, parsed.text);
    saveSession(name, next);
    process.stdout.write(`[cupid note recorded on ${name}] ${parsed.text}\n`);
  });
}

function parseNudgeArgs(args) {
  if (args.length === 0 || typeof args[0] !== "string" || args[0].length === 0) {
    throw new Error('Usage: tune nudge "<text>" [--session <name>]');
  }
  const result = { text: args[0], session: undefined };
  for (let index = 1; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else {
      throw new Error(`Unknown nudge flag: ${token}`);
    }
  }
  return result;
}

async function runJudge(args) {
  const parsed = parseJudgeArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule((tune) => {
    const next = tune.appendJudgeSnapshot(session, {
      dateHealthDelta: parsed.dateHealthDelta,
      note: parsed.note,
    });
    saveSession(name, next);
    const sign =
      parsed.dateHealthDelta >= 0 ? `+${parsed.dateHealthDelta}` : `${parsed.dateHealthDelta}`;
    process.stdout.write(
      `[judge snapshot recorded on ${name}] ${sign} health: ${parsed.note ?? "Manual judge snapshot."}\n`,
    );
  });
}

function parseJudgeArgs(args) {
  if (args.length === 0) {
    throw new Error(
      'Usage: tune judge <dateHealthDelta> [--note "<text>"] [--session <name>]. Delta is an integer in [-50, 50]. Negative values cool the date.',
    );
  }
  const result = { dateHealthDelta: undefined, note: undefined, session: undefined };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--note") {
      result.note = requireFlagValue(args, index);
      index += 1;
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else if (result.dateHealthDelta === undefined) {
      const parsed = Number(token);
      if (!Number.isFinite(parsed) || !Number.isInteger(parsed)) {
        throw new Error(`Judge delta must be an integer, got "${token}".`);
      }
      result.dateHealthDelta = parsed;
    } else {
      throw new Error(`Unknown judge flag: ${token}`);
    }
  }
  if (result.dateHealthDelta === undefined) {
    throw new Error("Judge command requires a dateHealthDelta integer as the first argument.");
  }
  return result;
}

async function runPreview(args) {
  const parsed = parsePreviewArgs(args);
  const name = parsed.session ?? requireActiveSessionName();
  const session = loadSession(name);
  await withTuneModule((tune) => {
    const speakerRole =
      partnerControlOf(session) === "ai" ? tune.nextLiveSpeakerRole(session) : undefined;
    const preview = tune.previewMemberTurnPacket(session, { speakerRole });
    if (parsed.section === "system") {
      process.stdout.write(`${preview.packet.system}\n`);
    } else if (parsed.section === "thread") {
      const lines = preview.packet.messages.map((message) => {
        const content =
          typeof message.content === "string"
            ? message.content
            : message.content
                .map((part) => (part.type === "text" ? part.text : `[${part.type}]`))
                .join(" ");
        return `[${message.role}] ${content}`;
      });
      process.stdout.write(`${lines.join("\n\n")}\n`);
    } else {
      process.stdout.write(`${preview.packet.prompt}\n`);
    }
  });
}

function parsePreviewArgs(args) {
  const result = { section: "prompt", session: undefined };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--system") {
      result.section = "system";
    } else if (token === "--thread") {
      result.section = "thread";
    } else if (token === "--prompt") {
      result.section = "prompt";
    } else if (token === "--session") {
      result.session = requireFlagValue(args, index);
      index += 1;
    } else {
      throw new Error(`Unknown preview flag: ${token}`);
    }
  }
  return result;
}

async function runShow(args) {
  const parsed = parseShowArgs(args);
  const name = parsed.name ?? requireActiveSessionName();
  const session = loadSession(name);

  await withTuneModule((tune) => {
    const focus = tune.findMemberById(session.focusMemberId);
    const partner = tune.findMemberById(session.partnerMemberId);
    const scenario = tune.findScenarioById(session.scenarioId);
    const focusRequest =
      session.focusRequestId === undefined
        ? undefined
        : tune.findMemberRequestById(session.focusRequestId);

    const header = [
      `Session: ${name}`,
      `  Focus:    ${focus.name} (${focus.id})`,
      `  Partner:  ${partner.name} (${partner.id})`,
      `  Scenario: ${scenario.title} (${scenario.id})`,
      `  Mode:     ${partnerControlOf(session) === "ai" ? "AI controls both members" : "manual partner control"}`,
      focusRequest === undefined
        ? `  Request:  (none)`
        : `  Request:  ${focusRequest.id} — ${focusRequest.text}`,
      `  Messages: ${session.messages.length}`,
    ].join("\n");

    process.stdout.write(`${header}\n\n`);

    if (parsed.showPrompt) {
      if (typeof session.lastPromptSystem !== "string") {
        process.stdout.write("(no prompt recorded yet, run `tune turn` or `tune say` first)\n");
      } else {
        process.stdout.write(`--- last system prompt ---\n${session.lastPromptSystem}\n`);
      }
      return;
    }

    const transcript = tune.formatTranscriptForReading(session, {
      focusName: focus.firstName,
      partnerName: partner.firstName,
    });
    process.stdout.write(`${transcript}\n`);
  });
}

function parseShowArgs(args) {
  const result = { name: undefined, showPrompt: false };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (token === "--prompt") {
      result.showPrompt = true;
    } else if (token === "--name" || token === "--session") {
      result.name = requireFlagValue(args, index);
      index += 1;
    } else {
      throw new Error(`Unknown show flag: ${token}`);
    }
  }
  return result;
}

async function generateAndPrint(name, sessionBeforeReply, tune, options) {
  const generationOptions = resolveGenerationOptions(options.generationOptions ?? {});
  const runtimeConfig = resolveRuntimeConfig(options.config ?? {});
  const result = await tune.generateMemberReply(sessionBeforeReply, {
    config: runtimeConfig,
    generationOptions,
    speakerRole: "focus",
  });
  saveSession(name, result.session);
  printGenerationResult(result, {
    ...options,
    runtimeConfig,
    generationOptions,
  });
}

function printGenerationResult(result, options) {
  if (options.showSystem) {
    process.stdout.write(
      `--- system prompt ---\n${result.preview.packet.system}\n--- end system prompt ---\n\n`,
    );
  } else if (options.showPrompt) {
    process.stdout.write(
      `--- full prompt ---\n${result.preview.packet.prompt}\n--- end prompt ---\n\n`,
    );
  }

  process.stdout.write(`${result.preview.speakerMember.firstName}: ${result.replyText}\n`);

  const generationOptions = options.generationOptions ?? {};
  const runtimeConfig = options.runtimeConfig ?? resolveRuntimeConfig(options.config ?? {});
  const stats = [
    `model: ${result.modelId} (${result.providerMode})`,
    runtimeConfig.reasoningLevel === undefined
      ? null
      : `reasoning: ${runtimeConfig.reasoningLevel}`,
    `tokens approx: ${result.approximatePromptTokens}`,
    generationOptions.deepseekRoleplayThinking === true
      ? "deepseek roleplay thinking: on"
      : generationOptions.deepseekRoleplayThinking === false
        ? "deepseek roleplay thinking: off"
        : null,
    result.retried ? `retried: ${result.retryReason}` : null,
  ]
    .filter((part) => part !== null)
    .join(" | ");
  process.stdout.write(`(${stats})\n`);

  for (const warning of result.warningMessages) {
    process.stdout.write(`note: ${warning}\n`);
  }
}

function isRuntimeConfigFlag(token) {
  return [
    "--provider",
    "--chat-model",
    "--gateway-key",
    "--gateway-base-url",
    "--reasoning",
    "--timeout-ms",
  ].includes(token);
}

function isGenerationOptionFlag(token) {
  return ["--deepseek-roleplay-thinking", "--no-deepseek-roleplay-thinking"].includes(token);
}

function readGenerationOptionFlag(token, generationOptions) {
  switch (token) {
    case "--deepseek-roleplay-thinking":
      generationOptions.deepseekRoleplayThinking = true;
      break;
    case "--no-deepseek-roleplay-thinking":
      generationOptions.deepseekRoleplayThinking = false;
      break;
    default:
      throw new Error(`Unknown generation option: ${token}`);
  }
}

function readRuntimeConfigFlag(args, index, config) {
  const token = args[index];
  const value = requireFlagValue(args, index);

  switch (token) {
    case "--provider":
      config.aiProvider = value;
      break;
    case "--chat-model":
      config.chatModel = value;
      break;
    case "--gateway-key":
      config.gatewayApiKey = value;
      break;
    case "--gateway-base-url":
      config.gatewayBaseURL = value;
      break;
    case "--reasoning":
      config.reasoningLevel = value;
      break;
    case "--timeout-ms": {
      const parsed = Number(value);
      if (!Number.isInteger(parsed) || parsed <= 0) {
        throw new Error("--timeout-ms must be a positive integer.");
      }
      config.requestTimeoutMs = parsed;
      break;
    }
    default:
      throw new Error(`Unknown AI option: ${token}`);
  }

  return index + 1;
}

function resolveGenerationOptions(overrides) {
  const generationOptions = { deepseekRoleplayThinking: true };
  const deepseekRoleplayThinkingRaw =
    overrides.deepseekRoleplayThinking ?? process.env.TUNE_DEEPSEEK_ROLEPLAY_THINKING;

  if (isTruthyFlag(deepseekRoleplayThinkingRaw)) {
    generationOptions.deepseekRoleplayThinking = true;
  } else if (isFalsyFlag(deepseekRoleplayThinkingRaw)) {
    generationOptions.deepseekRoleplayThinking = false;
  }

  return generationOptions;
}

function resolveRuntimeConfig(overrides) {
  const config = {};
  const provider = normalizeOptionalValue(overrides.aiProvider ?? process.env.TUNE_PROVIDER);
  const chatModel = normalizeOptionalValue(overrides.chatModel ?? process.env.TUNE_CHAT_MODEL);
  const gatewayApiKey = normalizeOptionalValue(
    overrides.gatewayApiKey ?? process.env.AI_GATEWAY_API_KEY,
  );
  const gatewayBaseURL = normalizeOptionalValue(
    overrides.gatewayBaseURL ?? process.env.AI_GATEWAY_BASE_URL,
  );
  const reasoningLevel = normalizeOptionalValue(
    overrides.reasoningLevel ?? process.env.TUNE_REASONING_LEVEL,
  );
  const timeoutMsRaw = overrides.requestTimeoutMs ?? process.env.TUNE_TIMEOUT_MS;

  if (provider !== undefined) {
    if (provider !== "ollama" && provider !== "gateway") {
      throw new Error("--provider must be ollama or gateway.");
    }
    config.aiProvider = provider;
  }
  if (chatModel !== undefined) config.chatModel = chatModel;
  if (gatewayApiKey !== undefined) config.gatewayApiKey = gatewayApiKey;
  if (gatewayBaseURL !== undefined) config.gatewayBaseURL = gatewayBaseURL;
  if (reasoningLevel !== undefined) config.reasoningLevel = reasoningLevel;

  if (timeoutMsRaw !== undefined) {
    const parsed = typeof timeoutMsRaw === "number" ? timeoutMsRaw : Number(timeoutMsRaw);
    if (!Number.isInteger(parsed) || parsed <= 0) {
      throw new Error("TUNE_TIMEOUT_MS must be a positive integer.");
    }
    config.requestTimeoutMs = parsed;
  }

  if (config.aiProvider === undefined && config.gatewayApiKey !== undefined) {
    config.aiProvider = "gateway";
  }

  if (config.aiProvider === "gateway") {
    if (config.chatModel === undefined) {
      config.chatModel = DEFAULT_TUNE_GATEWAY_CHAT_MODEL;
    }
    if (config.reasoningLevel === undefined && isDeepSeekV4TuneModel(config.chatModel)) {
      config.reasoningLevel = DEFAULT_TUNE_DEEPSEEK_REASONING_LEVEL;
    }
  }

  return config;
}

function isDeepSeekV4TuneModel(modelId) {
  return modelId === DEFAULT_TUNE_GATEWAY_CHAT_MODEL || modelId === DEEPSEEK_V4_PRO_MODEL;
}

function isTruthyFlag(value) {
  return value === true || value === "1" || value === "true" || value === "yes" || value === "on";
}

function isFalsyFlag(value) {
  return value === false || value === "0" || value === "false" || value === "no" || value === "off";
}

function normalizeOptionalValue(value) {
  if (typeof value !== "string") {
    return value;
  }
  const trimmed = value.trim();
  return trimmed.length === 0 ? undefined : trimmed;
}

function requireFlagValue(args, index) {
  const value = args[index + 1];
  if (typeof value !== "string" || value.length === 0 || value.startsWith("--")) {
    throw new Error(`${args[index]} requires a value.`);
  }
  return value;
}

function formatPartnerEcho(session, tune) {
  const partner = tune.findMemberById(session.partnerMemberId);
  const lastMessage = session.messages[session.messages.length - 1];
  if (lastMessage === undefined || lastMessage.kind !== "character") {
    return "(partner line recorded)\n";
  }
  return `${partner.firstName} (you): ${lastMessage.text}\n`;
}
