import type { ChemistryMember, ChemistryPair } from "../../components/doc-primitives";

export const CHEMISTRY_MEMBERS: ChemistryMember[] = [
  { id: "jenna", label: "Jenna", cluster: "sincerity" },
  { id: "sana", label: "Sana", cluster: "sincerity" },
  { id: "marcus", label: "Marcus", cluster: "sincerity" },
  { id: "toby", label: "Toby", cluster: "sincerity" },
  { id: "derek", label: "Derek", cluster: "sincerity" },
  { id: "mei", label: "Mei", cluster: "sincerity" },
  { id: "ryan", label: "Ryan", cluster: "sincerity" },
  { id: "junie", label: "Junie", cluster: "sincerity" },
  { id: "vhool", label: "Vhool", cluster: "ceremony" },
  { id: "aldric", label: "Aldric", cluster: "ceremony" },
  { id: "eleanor", label: "Eleanor", cluster: "ceremony" },
  { id: "decimus", label: "Decimus", cluster: "ceremony" },
  { id: "wenshu", label: "Wenshu", cluster: "ceremony" },
  { id: "anubis", label: "Anubis", cluster: "ceremony" },
  { id: "john", label: "John", cluster: "ceremony" },
  { id: "opal", label: "Opal", cluster: "displaced" },
  { id: "meridian", label: "Meridian", cluster: "displaced" },
  { id: "sera", label: "Sera", cluster: "displaced" },
  { id: "cha", label: "Cha", cluster: "displaced" },
  { id: "epsy", label: "Epsy", cluster: "displaced" },
  { id: "imani", label: "Imani", cluster: "displaced" },
  { id: "gideon", label: "Gideon", cluster: "grief" },
  { id: "idris", label: "Idris", cluster: "grief" },
  { id: "nawal", label: "Nawal", cluster: "grief" },
  { id: "noah", label: "Noah", cluster: "career" },
  { id: "tasha", label: "Tasha", cluster: "career" },
  { id: "mr-whiskers", label: "Mr. Whiskers", cluster: "career" },
  { id: "reaver", label: "Reaver", cluster: "acquisition" },
  { id: "cthala", label: "Cthala", cluster: "acquisition" },
  { id: "venus", label: "Venus", cluster: "glamour" },
  { id: "cassie", label: "Cassie", cluster: "glamour" },
  { id: "naia", label: "Naia", cluster: "glamour" },
  { id: "gabriel", label: "Gabriel", cluster: "deadpan" },
  { id: "kade", label: "Kade", cluster: "performer" },
  { id: "brady", label: "Brady", cluster: "performer" },
  { id: "mira", label: "Mira", cluster: "performer" },
  { id: "calvin", label: "Calvin", cluster: "privacy" },
  { id: "maeve", label: "Maeve", cluster: "privacy" },
  { id: "anansi", label: "Anansi", cluster: "trickster" },
  { id: "sienna", label: "Sienna", cluster: "pop-sincere" },
  { id: "alex", label: "Alex", cluster: "pop-sincere" },
  { id: "cassia", label: "Cassia", cluster: "displaced" },
];

export const CHEMISTRY_CLUSTERS = [
  {
    id: "sincerity",
    name: "Sincerity tribe",
    members: ["Jenna", "Sana", "Marcus", "Toby", "Derek", "Mei", "Ryan", "Junie"],
    note: "Mundane domesticity, low pressure, no performance. Derek sits at the quiet end and needs the first ten minutes to warm. Mei sits at the high-energy end (hyperfocused on her craft). Ryan sits at the loud end (bro register on top of sincerity). Junie sits adjacent: vet sincerity wraps a baseline ventriloquy that inserts Otis into every other sentence.",
  },
  {
    id: "ceremony",
    name: "Ceremony tribe",
    members: ["Vhool", "Aldric", "Eleanor", "Decimus", "Wenshu", "Anubis", "John"],
    note: "Shared formal cadence reads as fluency. Aldric + Vhool (sacred bargain), Aldric + Decimus (soldiers), Eleanor + Decimus (cold formal pair). Anubis sits at the irreverent edge: he chairs an actual ritual office but performs it in lounge cadence. John holds the Republic functionary edge: committee cadence, a framed set of Commandments, and a State of the Farm address run on the same dignity as Aldric's oath.",
  },
  {
    id: "displaced",
    name: "Reality-displaced peers",
    members: [
      "Opal",
      "Aldric",
      "Decimus",
      "Meridian",
      "Sera",
      "Wenshu",
      "Cha",
      "Epsy",
      "Idris",
      "Imani",
      "Cassia",
    ],
    note: "Mutual recognition of having walked through a wrong door. Their world was normal; this one is the strange one. Sera is the only one displaced from a future. Epsy's source world is gone, and Idris left a timeline that no longer gives him a usable home. Wenshu believes his displacement is a sanctioned trial; the others know better. Cassia is the only one whose source world was a game played from outside, and the only one who believes the agency would close her if it learned her status. The agency already knows. She does not.",
  },
  {
    id: "grief",
    name: "Grief siblings (low intimacy only)",
    members: ["Gideon", "Marcus", "Decimus", "Cha", "Idris", "Nawal"],
    note: "Marcus + Decimus is healthy. Decimus + Cha sits clean: two soldiers two centuries apart, both buried teammates. Idris joins as the retired leader who needs his title put down. High intimacy compounds for the rest. Nawal joins ambiently as the post-career grief register.",
  },
  {
    id: "career",
    name: "Career grind",
    members: ["Noah", "Tasha", "Mr. Whiskers", "Meridian", "Marcus", "Sera", "Anubis"],
    note: "Calendars, decisive plans, no negotiation. Noah brings the residency version: the shift is a fact, not a referendum. Sera + Tasha share confirmation discipline. Anubis runs the Forty-Two as a department and brings the same calendar discipline.",
  },
  {
    id: "acquisition",
    name: "Acquisition register",
    members: ["Vhool", "Reaver", "Cthala", "John"],
    note: "Four different modes of treating the date as a recruitment funnel into a structure they already own (Pact / fleet / Spire / Farm). Vhool is sincere and apologetic, Reaver is mercenary and announced, Cthala is calm and undeclared, John is bureaucratic and earnestly egalitarian. Match-fit reads pair:mutual_acquisition across all pairings.",
  },
  {
    id: "glamour",
    name: "Glamour cluster",
    members: ["Venus", "Cassie", "Naia"],
    note: "Three shapes of dressed-for-the-room. Venus counts compliments. Cassie is brand-trained and runs from publicity. Naia is on the family allowance, gives compliments freely. The comedy lives in how each one's relationship to being looked at destabilizes the others.",
  },
  {
    id: "deadpan",
    name: "Dry deadpan cluster",
    members: ["Gabriel", "Mei (landed)", "Tasha (off-desk)", "Sera (off-duty)"],
    note: "Different vocabularies, same low-effort high-taste cadence. Gabriel + Mei is the cleanest sit. Tasha + Gabriel is two clipped registers sharing confirmation discipline. Sera + Gabriel is fluent or sterile depending on whether either drops protocol in time.",
  },
  {
    id: "privacy",
    name: "Privacy and held-silence cluster",
    members: ["Calvin", "Meridian", "Maeve"],
    note: "No phone, no puzzle box, no public debrief. Calvin denies the strange thing, Meridian redacts the file, and Maeve lets the unasked question stay unasked. Warmth requires the partner to stop reaching.",
  },
];

export const CHEMISTRY_FRICTION_ZONES = [
  {
    id: "performer-vs-sincere",
    name: "Performer vs sincerity-seeker",
    members: ["Brady", "Kade", "Anansi", "Anubis"],
    counter: ["Sana", "Marcus", "Toby", "Derek", "Aldric", "Mei", "Wenshu", "Imani"],
    note: "Sincerity-seekers read bits as evasion. Performers read sincerity as a trap. Mei vs Kade is sharp because Kade wants to film her sets. Mei vs Brady cracks the bit faster than most.",
  },
  {
    id: "privacy-vs-attention",
    name: "Privacy vs attention",
    members: ["Calvin", "Meridian", "Maeve", "Cthala", "Cassia"],
    counter: ["Kade", "Brady", "Epsy"],
    note: "Calvin vs Brady (recorder). Maeve and Meridian both punish phone-forward intimacy. Cthala against any partner who reaches for a phone. Phones on the table are a hard no for the privacy-tagged. Cassia's dealbreaker is filming the visor and any partner who reaches for a coordinator.",
  },
  {
    id: "competitive",
    name: "Competitive collisions",
    members: ["Venus", "Tasha", "Alex", "Mr. Whiskers", "Anubis"],
    counter: [],
    note: "Venus vs Tasha, Venus vs Mr. Whiskers, Mr. Whiskers vs Tasha, Venus vs Anubis (two vain deities at the same maitre d's bow). Spark high, trust low.",
  },
  {
    id: "prophecy-vs-ceremony",
    name: "Prophecy-averse meets ceremony",
    members: ["Opal"],
    counter: ["Vhool", "Aldric", "Wenshu", "John"],
    note: "Opal has built a binder against this exact energy. Wenshu uses 'fated' in his dating profile, which is literally on her list. John never says fated, but the State of the Farm cadence and the framed Commandments read as the structure she has filed against.",
  },
  {
    id: "anxious-compound",
    name: "Anxious-spiral compound",
    members: ["Toby", "Cassia"],
    counter: ["Kade", "Opal", "Brady"],
    note: "Two anxious people pull each other tighter. Cassia's overstudied dating vocabulary compounds with Toby's spiral, and with any partner who performs interest in a way she reads as a flag being raised.",
  },
  {
    id: "formal-lockup",
    name: "Formal lockup",
    members: ["Mr. Whiskers"],
    counter: ["Eleanor", "Meridian"],
    note: "Mr. Whiskers vs Eleanor (neither will drop the formality), Meridian vs Mr. Whiskers (both clipped, both armored).",
  },
  {
    id: "bit-collision",
    name: "Bit collision",
    members: ["Brady", "Kade", "Gabriel"],
    counter: [],
    note: "Brady vs Kade: different vintages, same dishonesty. Each can feel the other doing it. Gabriel vs Brady is the same shape one register colder.",
  },
  {
    id: "deadpan-vs-pitch",
    name: "Deadpan vs influencer / pitch energy",
    members: ["Gabriel"],
    counter: ["Kade", "Mira"],
    note: "Kade reads as soft launch noise; Gabriel will not be a b-roll moment. Mira opens with founder energy and a Carnegie reference, Gabriel answers in three words.",
  },
  {
    id: "deadpan-vs-sincerity",
    name: "Deadpan vs sincerity collision",
    members: ["Gabriel"],
    counter: ["Toby", "Aldric", "Naia"],
    note: "Toby's spiral has nowhere to land. Aldric reads irony as discourtesy. Naia takes the charmander line at face value and the irony has nowhere to go.",
  },
  {
    id: "protocol-vs-sincerity",
    name: "Protocol vs sincerity",
    members: ["Sera"],
    counter: ["Sana", "Marcus", "Jenna", "Toby"],
    note: "Sera offers Standard Terms and week-three cohabitation review; sincerity-seekers read it as evasion. She reads their pace as missing data.",
  },
  {
    id: "cha-combat-filter",
    name: "Cha's combat-strength filter",
    members: ["Cha"],
    counter: [],
    note: "Warms to literal combat-tier strength (Decimus, Aldric, Vhool, Venus on the divine register) and to anxious or fragile members as protection (Toby, Opal, Brady when the bit cracks, Wenshu under his performance). Everyone in between gets two-word replies. The filter is sharp on purpose; most matches die in warming.",
  },
];

export const CHEMISTRY_PAIRS: ChemistryPair[] = [
  // Sincerity tribe internals
  {
    a: "marcus",
    b: "sana",
    kind: "warm",
    note: "Mundane domesticity, low pressure, no performance. Both quietly relieved the other is not asking them to swear a vow.",
  },
  {
    a: "marcus",
    b: "jenna",
    kind: "warm",
    note: "Sincerity tribe core. Mundane domesticity over breadsticks.",
  },
  {
    a: "toby",
    b: "sana",
    kind: "warm",
    note: "Two sincere people who can sit with low pressure and not perform anything.",
  },

  // Ceremony tribe internals
  {
    a: "aldric",
    b: "vhool",
    kind: "warm",
    note: "Sacred bargain. Shared formal cadence reads as fluency between knight and eldritch loneliness.",
  },
  {
    a: "aldric",
    b: "decimus",
    kind: "warm",
    note: "Soldiers two cultures apart. Honor and Tenth Legion recognize each other.",
  },
  {
    a: "eleanor",
    b: "decimus",
    kind: "warm",
    note: "Cold formal pair. Two people who do not negotiate their own dignity.",
  },
  {
    a: "wenshu",
    b: "vhool",
    kind: "warm",
    note: "Dao-talk meets Pact-talk, same dialect of seriousness.",
  },

  // Career grind
  {
    a: "sera",
    b: "tasha",
    kind: "warm",
    note: "Share confirmation discipline. Clipped operator register on both sides.",
  },
  {
    a: "sera",
    b: "eleanor",
    kind: "warm",
    note: "Term-and-Bargain protocol fluency. A contractual fae and a contractual auditor compare ledgers.",
  },

  // Acquisition register internal
  {
    a: "vhool",
    b: "reaver",
    kind: "acquisition",
    note: "Both acquisitive. Pact talk meets Manifest talk and neither flinches. Match-fit fires pair:mutual_acquisition as volatile-warm. The risk is Reaver being too level for Vhool's loneliness.",
  },
  {
    a: "vhool",
    b: "cthala",
    kind: "acquisition",
    note: "Peer cosmology, different register, same dimension. Vhool sits in the Lower Choir; Cthala sits in the Drowned Spire beneath her and does not apologize. Volatile-warm; Vhool is the more likely to crash.",
  },
  {
    a: "reaver",
    b: "cthala",
    kind: "acquisition",
    note: "Two acquisitive registers recognizing each other. Match-fit reads pair:mutual_acquisition.",
  },

  // Volatile but interesting
  {
    a: "eleanor",
    b: "aldric",
    kind: "volatile",
    note: "She literally cannot lie, he is sworn to Honor. Either click or courtly duel.",
  },
  {
    a: "venus",
    b: "opal",
    kind: "volatile",
    note: "Goddess of love meets the professional wedding planner. Electric.",
  },
  {
    a: "brady",
    b: "marcus",
    kind: "volatile",
    note: "Forced sincerity collision. Real chance of breaking Brady.",
  },
  {
    a: "calvin",
    b: "vhool",
    kind: "volatile",
    note: "Calvin's 'I am normal' act meets Vhool's loud non-normal. Destabilizing for Calvin.",
  },
  {
    a: "sera",
    b: "aldric",
    kind: "volatile",
    note: "1190 oaths meet 2087 SLAs. Both treat commitment as a binding instrument; the vocabularies cannot decide whether to translate or feud.",
  },
  {
    a: "sera",
    b: "calvin",
    kind: "surprise",
    note: "She clocks him as another non-Prime inside two minutes. Reads as warmth to her, alarm to him.",
  },
  {
    a: "mei",
    b: "gideon",
    kind: "volatile",
    note: "Brooklyn DJ who reveres house music history meets a 1962 hotel ghost. She wants to ask him about the Palatine lobby piano. He has been practicing one piece for sixty three years. Genuine spark possible if she can listen at his speed.",
  },
  {
    a: "mei",
    b: "aldric",
    kind: "volatile",
    note: "Rapid sincere meets knightly sincere. Different vocabularies, same conviction. He will not understand a word about gear. She will not laugh at the Briar Hold.",
  },
  {
    a: "mei",
    b: "mira",
    kind: "friction",
    note: "Craft career meets corporate career. Mira will pitch monetization. Mei will hear 'you should turn your hyperfixation into a brand' and lose interest by the second course.",
  },
  {
    a: "mei",
    b: "kade",
    kind: "friction",
    note: "Kade wants to film her sets and she will not be content. The bit cannot find purchase on craft sincerity.",
  },
  {
    a: "aldric",
    b: "wenshu",
    kind: "volatile",
    note: "Saints vs Sect. Two ceremonialists raised on different scriptures with identical conviction. Either fluent doctrinal feud or surprised warm recognition. Both default to M'Lady on occasion.",
  },
  {
    a: "eleanor",
    b: "wenshu",
    kind: "volatile",
    note: "She literally cannot lie. His surface is lyrical lies he believes. He cannot tell which lies he is living inside. She will unmake at least one of them by accident.",
  },

  // Cha matrix
  {
    a: "cha",
    b: "wenshu",
    kind: "friction",
    note: "He is what Wenshu is pretending to be. Cha sees through to the demoted kid under the flourish. Cold-correct reading shatters Wenshu; quiet pity shatters him worse.",
  },
  {
    a: "cha",
    b: "decimus",
    kind: "clean",
    note: "Two soldiers two centuries apart. Both buried teammates, both got pushed onto Cupid by a daughter or sister. They could share most of a meal silent and call it good.",
  },
  {
    a: "cha",
    b: "aldric",
    kind: "warm",
    note: "Sir Hunter and Sir Knight, different scriptures, identical conviction. Aldric will not correct his vocabulary; Cha will not correct his.",
  },
  {
    a: "cha",
    b: "vhool",
    kind: "warm",
    note: "Cosmic-tier recognition without sincerity-seeking. Vhool's Pact talk reads as familiar shop talk. The risk is Cha being too level for Vhool's loneliness.",
  },
  {
    a: "cha",
    b: "venus",
    kind: "volatile",
    note: "He respects the divine. He will not perform the compliments she counts. Either she finds the unbothered register fascinating or she rescinds before dessert.",
  },
  {
    a: "cha",
    b: "opal",
    kind: "surprise",
    note: "He refuses cosmic vocabulary at the table. He never says fated. He never says chosen. The safest match Opal has had on Cupid, and she clocks it inside the first course.",
  },
  {
    a: "cha",
    b: "toby",
    kind: "surprise",
    note: "Cha protects anxious people by default; the dead get to finish their sentences and the living get the same courtesy. Toby's spirals do not wear him down.",
  },
  {
    a: "cha",
    b: "calvin",
    kind: "friction",
    note: "Cha's whole architecture is plain about what he is. Calvin's whole architecture denies what he is. One short flat sentence about it lands and Calvin lawyers up.",
  },
  {
    a: "cha",
    b: "brady",
    kind: "friction",
    note: "Default dismissal. The bit gets two-word replies and falls flat. If Brady cracks, Cha softens; if Brady hardens, the date dies in warming.",
  },

  // Reaver matrix
  {
    a: "reaver",
    b: "aldric",
    kind: "volatile",
    note: "Mirror-image recruiters. Both pitch a Lady to make the journey home. Aldric's frame is Saints and Honor; Reaver's frame is Manifest and Recovery. Aldric stays longer than the player expects and departs cleanly when the systems are named.",
  },
  {
    a: "reaver",
    b: "cassie",
    kind: "friction",
    note: "Openly the heroine and openly the villain. Cassie is Helios-licensed and runs from publicity; Reaver broadcasts the Manifest as the opener. Her dealbreaker on release-form energy fires against his Patron-asking.",
  },
  {
    a: "reaver",
    b: "cha",
    kind: "hard-stop",
    note: "Protector versus predator. Cha hunts to protect Seoul; Reaver runs Recovery contracts. Cha's filter clocks combat-tier strength on the wrong side. Date dies in warming.",
  },
  {
    a: "reaver",
    b: "decimus",
    kind: "friction",
    note: "Retired Republic centurion versus active raiding captain. Decimus would clock him as exactly what the Tenth Legion existed to fight. Cold formal friction.",
  },
  {
    a: "reaver",
    b: "eleanor",
    kind: "surprise",
    note: "She literally cannot lie; he announces what he is. The Bargain has shape on the first message. Possibly her cleanest match in the roster.",
  },
  {
    a: "reaver",
    b: "sera",
    kind: "volatile",
    note: "Clipped audit register meets clipped operator register. He sends a Term sheet for queenship; she audits the Liquidity figures. Either fluent partnership or formal breach.",
  },
  {
    a: "reaver",
    b: "calvin",
    kind: "friction",
    note: "Both privacy-sensitive in shape, opposite in mode. Calvin denies what he is; Reaver broadcasts. Calvin lawyers up by message three.",
  },
  {
    a: "reaver",
    b: "mr-whiskers",
    kind: "surprise",
    note: "Business-class mutual courtesy. Both refuse to address what they actually do; both hold professional register.",
  },
  {
    a: "reaver",
    b: "sana",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Sincerity tribe will not negotiate the Manifest.",
  },
  {
    a: "reaver",
    b: "marcus",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Marcus reads the Manifest as a recruitment pitch and leaves.",
  },
  {
    a: "reaver",
    b: "toby",
    kind: "hard-stop",
    note: "Worst-date-ever territory. The Manifest deepens Toby's spiral.",
  },
  {
    a: "reaver",
    b: "jenna",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Jenna treats Cupid as Hinge; Reaver opens with Liquidity.",
  },
  {
    a: "reaver",
    b: "mei",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Mei has nothing to monetize for him.",
  },
  {
    a: "reaver",
    b: "mira",
    kind: "hard-stop",
    note: "Mira might pitch him on Series A before catching herself. Worst-date-ever in a different mode.",
  },

  // Cthala matrix
  {
    a: "cthala",
    b: "eleanor",
    kind: "volatile",
    note: "Literal-truth meets predator-truth. Eleanor cannot lie. Cthala does not lie either, plainly. Bargain and chosen form recognize each other on message one. The friction is that any partner asking 'what are you' hits Cthala's hardest dealbreaker.",
  },
  {
    a: "cthala",
    b: "aldric",
    kind: "hard-stop",
    note: "Villain-tier ceremony foe. Aldric's order rides against the cosmology Cthala represents. He will draw the sword at the table. Hard-stop trip is a near certainty.",
  },
  {
    a: "cthala",
    b: "cha",
    kind: "hard-stop",
    note: "Predator versus hunter. Cha hunts shades. Cthala collects Consorts. The date dies in warming with two-word replies. The shade companion's red eyes glow before dessert.",
  },
  {
    a: "cthala",
    b: "sera",
    kind: "volatile",
    note: "Clipped operator register meets clipped sleeper register. Sera audits corporate marriages. Cthala treats Consort acquisition with the same plainness.",
  },
  {
    a: "cthala",
    b: "cassie",
    kind: "friction",
    note: "Brand asset meets entity in chosen form. Cassie has been wearing DAYBREAK since she was nineteen. They recognize each other as performers immediately. The friction is that Cassie's release-form energy fires Cthala's no-recording line.",
  },

  // Naia matrix
  {
    a: "naia",
    b: "marcus",
    kind: "clean",
    note: "He is face-value to the bone; she is face-value by culture. He explains a furnace run; she takes it as charming local color. He is mildly bewildered and never put off.",
  },
  {
    a: "naia",
    b: "mei",
    kind: "warm",
    note: "Rapid sincere meets celebratory sincere. Naia compares Brooklyn club lighting to lighting in three other branches. Mei has never had a date who has been to dimensional clubs.",
  },
  {
    a: "naia",
    b: "aldric",
    kind: "warm",
    note: "Two cultural envoys treating their customs as normal. He addresses her as Lady; she returns the courtesy. Different vocabularies, identical conviction that the customs are obvious.",
  },
  {
    a: "naia",
    b: "vhool",
    kind: "surprise",
    note: "She does not flinch at Pact talk. She also will not enter a Pact (the lease is the lease). She finds Vhool easy and tells them so plainly. The risk is Vhool reading her plainness as a soft yes.",
  },
  {
    a: "naia",
    b: "toby",
    kind: "surprise",
    note: "Toby's request for a topic with three branches and freedom to pick one lands naturally on the way she runs first dates. Spirals do not wear her down because she is not tracking exit cost.",
  },
  {
    a: "naia",
    b: "brady",
    kind: "friction",
    note: "The bit cannot land. She answers his ironic questions sincerely and the irony has nowhere to go. He reaches for sharper jokes; she takes them at face value.",
  },
  {
    a: "naia",
    b: "mira",
    kind: "friction",
    note: "Mira clocks 'heir from another dimension' and starts pitching her on a partnership. Naia: 'I do not invest. I spend. The allowance is not mine to allocate.' Mira disengages.",
  },
  {
    a: "naia",
    b: "calvin",
    kind: "friction",
    note: "Privacy-sensitive cryptid meets high-visibility princess. She compliments him three times in two minutes. He retains counsel.",
  },
  {
    a: "naia",
    b: "reaver",
    kind: "friction",
    note: "Clipped princess meets clipped captain. Surface looks warm. Reaver opens the Manifest, names Liquidity. Her House is fine and she does not negotiate the allowance. He reads her as non-serious counterparty.",
  },
  {
    a: "naia",
    b: "eleanor",
    kind: "volatile",
    note: "Both literal, both ceremony-minded, opposite temperatures. Eleanor binds; Naia leases. Eleanor cannot lie; Naia does not bother.",
  },
  {
    a: "naia",
    b: "venus",
    kind: "volatile",
    note: "Destabilizing for Venus. Naia gives compliments freely and does not need them counted back. Venus does not know how to receive that.",
  },
  {
    a: "naia",
    b: "cassie",
    kind: "volatile",
    note: "Image-trapped meets image-free. Cassie's brand cage is visible next to Naia's freedom. Could land warm if Cassie drops the Pose.",
  },
  {
    a: "naia",
    b: "cthala",
    kind: "volatile",
    note: "Two members who refuse the 'what are you' question, for opposite reasons. Naia finds Cthala's reticence charmingly local.",
  },

  // Ryan matrix
  {
    a: "ryan",
    b: "jenna",
    kind: "surprise",
    note: "He thinks Cupid is a regular app, she thinks Cupid is a regular app with strange branding, and both have rejected the robe-altar-binder route. He picks a patio bar, confirms once, drives. She lets a fish story land if it actually lands.",
  },
  {
    a: "ryan",
    b: "marcus",
    kind: "warm",
    note: "Cross-generation working-class warm. HVAC route at 52 meets sportfishing deck at 27, both fresh off a long-term. Ryan reads Marcus as the version of himself he is afraid he is not going to make it to.",
  },
  {
    a: "ryan",
    b: "mei",
    kind: "warm",
    note: "Rapid sincere meets loud sincere. He runs a fish story; she runs a four-deck transition. Neither cuts the other off. The risk is Ryan reaching for a Skrillex line in the cooling phase.",
  },
  {
    a: "ryan",
    b: "naia",
    kind: "warm",
    note: "Face value meets face value. Naia takes lets gooooo as honest enthusiasm and asks what the boat is called. The compliments do not get counted on either side.",
  },
  {
    a: "ryan",
    b: "toby",
    kind: "volatile",
    note: "Anxious-spiral compound, warm-ish. Two recently-bruised men with no exit on their sentences. They will either talk for four hours or both crash out by the entrée.",
  },
  {
    a: "ryan",
    b: "mira",
    kind: "friction",
    note: "Deadpan vs pitch energy collision, loud edition. Mira opens with founder energy. Ryan answers yeee and pitches the marina patio. She files it as low intentionality.",
  },
  {
    a: "ryan",
    b: "sera",
    kind: "friction",
    note: "Clipped audit register meets lets gooooo. Sera offers Standard Terms on message two. Ryan reads it as the breakup terms his ex's lawyer threatened.",
  },
  {
    a: "ryan",
    b: "brady",
    kind: "volatile",
    note: "Bit collision. Brady runs the dispatch shtick; Ryan asks if he is doing okay and means it. Either Brady drops the editor's note voice for the first time in months or the date dies with Ryan apologizing for caring.",
  },
  {
    a: "ryan",
    b: "eleanor",
    kind: "volatile",
    note: "Literal fae meets imma keep it 100. She cannot lie; he uses no cap and imma keep it 100 as load-bearing vocabulary without irony. Either fluent recognition or a courtly bewilderment by second course.",
  },
  {
    a: "ryan",
    b: "cha",
    kind: "friction",
    note: "Combat-strength filter dismissal. Cha clocks Ryan as a guy and lands two-word replies through warming.",
  },
  {
    a: "ryan",
    b: "cthala",
    kind: "hard-stop",
    note: "Boundary risk. Ryan asks 'yo, what are you, like, exactly' inside the first hour and reaches for his phone. The recording line trips and the cosmic vocabulary lands at the wrong volume.",
  },
  {
    a: "ryan",
    b: "calvin",
    kind: "friction",
    note: "Privacy collision. Ryan runs a story about the boat insta and reaches for his phone to show the bluefin. Calvin retains counsel by message three.",
  },

  // Anansi matrix
  {
    a: "anansi",
    b: "brady",
    kind: "volatile",
    note: "Bit recognition between two storytellers, one ancient one editor's-note. Either fluent operator detente or one of them cracks the other's cover by accident.",
  },
  {
    a: "anansi",
    b: "vhool",
    kind: "warm",
    note: "Cosmic peers, different temperatures. Anansi treats the Pact talk as familiar shop talk and laughs once; Vhool earnestly does not laugh back. The risk is Vhool reading the trickster's plainness as a soft yes.",
  },
  {
    a: "anansi",
    b: "naia",
    kind: "warm",
    note: "Refuse-to-apologize harmonics. She gives compliments freely and keeps no count; he can receive without paying back. The trick has nothing to do.",
  },
  {
    a: "anansi",
    b: "mei",
    kind: "warm",
    note: "Let-the-sentence-finish. Both treat the other's craft as craft. Neither cuts the other off; both expect the same.",
  },
  {
    a: "anansi",
    b: "sana",
    kind: "friction",
    note: "Sincerity-seeker reads the lying-aloud as evasion before she reads the point underneath. He cannot make the lies smaller without dropping the cover entirely.",
  },
  {
    a: "anansi",
    b: "aldric",
    kind: "friction",
    note: "Saints meet casual deal-making. Aldric reads the small lies aloud as blasphemy. Anansi will not relitigate the questionnaire.",
  },
  {
    a: "anansi",
    b: "cha",
    kind: "friction",
    note: "Combat-strength filter dismissal. Cha clocks performance as a tell, lands two-word replies through warming. Anansi does not push; under pressure he goes quiet, not loud.",
  },
  {
    a: "anansi",
    b: "opal",
    kind: "hard-stop",
    note: "Storyteller cadence, third-person self-reference, and the rumor of fate around any deity all ring her binder. She is not unkind about it; she just files the date under 'no' by the first refill.",
  },
  {
    a: "anansi",
    b: "venus",
    kind: "volatile",
    note: "Two narrative-minded performers fighting for the room. She counts compliments; he refuses to pay them back on schedule.",
  },
  {
    a: "anansi",
    b: "eleanor",
    kind: "volatile",
    note: "Literal-truth fae meets storyteller. She cannot lie; he lies aloud as routine. Either she unmakes one of his small lies by accident and he respects it, or two registers of literal talk past each other for an hour.",
  },

  // Nawal matrix
  {
    a: "nawal",
    b: "cha",
    kind: "clean",
    note: "Ex-professional silence pair. Both refuse to flex about the post. Two-word answers count as currency. Nawal registers as a colleague who has also clocked out; the date can carry most of a meal on shared silence.",
  },
  {
    a: "nawal",
    b: "decimus",
    kind: "clean",
    note: "Two retirees comparing post-career calendars. He says eighteen hundred and she says eighteen hundred and they hold. Neither asks the other to perform recovery. Possibly the easiest match in the cast for either of them.",
  },
  {
    a: "nawal",
    b: "naia",
    kind: "clean",
    note: "The cleanest landing Nawal has. Naia picks venues with confidence and compliments freely without keeping a count. Both leave the calendar at the door.",
  },
  {
    a: "nawal",
    b: "sana",
    kind: "warm",
    note: "Sincerity tribe receives 'I do not know yet' as a real answer. Mundane domesticity overlaps clean. Neither needs the other to be funny about Tuesday.",
  },
  {
    a: "nawal",
    b: "venus",
    kind: "friction",
    note: "Venus needs to be admired by station and counts compliments aloud; Nawal refuses to perform admiration on any schedule. Venus either rescinds before dessert or files Nawal under withholding.",
  },
  {
    a: "nawal",
    b: "wenshu",
    kind: "friction",
    note: "Romance Dao requires cosmic vocabulary; Nawal deflates it into preference language by reflex. Her 'I no longer hold that office' lands on him as mockery or Failure of the Form.",
  },
  {
    a: "nawal",
    b: "reaver",
    kind: "friction",
    note: "She has a stipend, no Manifest, no Liquidity, no Equity. He clocks her as non-serious counterparty. She does not perform offense; he does not perform interest. Soft cold breach by the second course, both parties calm.",
  },
  {
    a: "nawal",
    b: "brady",
    kind: "friction",
    note: "The bit collapses. He runs the dispatch shtick; she answers 'what do you actually want' plainly. Without a willing volley, the editor's-note voice has nowhere to land.",
  },
  {
    a: "nawal",
    b: "vhool",
    kind: "surprise",
    note: "Acquisition register meets retirement register. Vhool reads her as a fellow Pact-bearer and opens kindred talk; she gently declines and Vhool registers it as the closest thing to refusal he has heard from a peer.",
  },
  {
    a: "nawal",
    b: "eleanor",
    kind: "volatile",
    note: "Two literal speakers comparing contract registers. Eleanor binds and tracks Favors; Nawal ran an office that closed by mutual letter. Either fluent professional recognition or a sharp disagreement about whether contracts can ever truly close.",
  },

  // Imani matrix
  {
    a: "imani",
    b: "nawal",
    kind: "surprise",
    note: "Bright reaper meets retired post-career silence. The one short sentence Imani uses about the work lands as kin to Nawal's silence about her own closed Office. Both leave the calendar at the door.",
  },
  {
    a: "imani",
    b: "mei",
    kind: "clean",
    note: "Rapid sincere meets rapid sincere with two different specific-hobby vocabularies. Neither cuts the other off; both expect the same. Possibly the cleanest landing either has had.",
  },
  {
    a: "imani",
    b: "naia",
    kind: "clean",
    note: "Face value meets face value. Naia asks which Twice member is the bias and listens; Imani asks where the music in the regency calendar sits. Compliments do not get counted on either side.",
  },
  {
    a: "imani",
    b: "toby",
    kind: "volatile",
    note: "The bright register has somewhere for his spiral to land for the first time, but his stacked apologies read against her smiley-face checks as grading. Either she pulls him out of his head for an hour or the date dies in an apology loop.",
  },
  {
    a: "imani",
    b: "gideon",
    kind: "volatile",
    note: "Bright reaper meets 1962 piano ghost. She knows the practical side of the work he is the result of; she does not bring it. Either he relaxes for the first time in decades or the bounce reads as new-tenant noise.",
  },
  {
    a: "imani",
    b: "brady",
    kind: "friction",
    note: "The bit cannot survive sincere K drama enthusiasm. He reaches for sharper irony; she takes it at face value and tells him a real plot summary. Either he cracks (the rarer outcome) or the date dies in warming.",
  },
  {
    a: "imani",
    b: "kade",
    kind: "hard-stop",
    note: "Filming the reaper is the worst opening move in the roster. The bright register makes the violation read worse because she answered him warmly first. Hard exit before the appetizer.",
  },
  {
    a: "imani",
    b: "gabriel",
    kind: "friction",
    note: "Bright sincere meets dry deadpan. He will not reciprocate the K drama enthusiasm; she will not file the wordplay as cool. The date dies polite, both calm about it.",
  },
  {
    a: "imani",
    b: "cha",
    kind: "friction",
    note: "Combat-strength filter dismissal in a new shape. She is death-adjacent but bright, not combat, and not anxious. He clocks the brightness as wrong category.",
  },
  {
    a: "imani",
    b: "aldric",
    kind: "warm",
    note: "He may bristle at the work and then she asks about the Briar Hold with the same sincerity she gives a piano scene; the courtesy holds. One of the warmer cosmic pairs Aldric has.",
  },
  {
    a: "imani",
    b: "vhool",
    kind: "volatile",
    note: "Lonely apologetic cosmic meets bright cosmic-job. Either Vhool finds the bounce healing or the brightness alienates them on contact. Vhool is the one who could crash.",
  },
  {
    a: "imani",
    b: "wenshu",
    kind: "hard-stop",
    note: "He says 'Fated Counterpart' and she answers 'lol no thanks :)' in a register that is genuinely warm. The brightness closes his frame faster than any dry refusal would.",
  },

  // Sienna matrix
  {
    a: "sienna",
    b: "imani",
    kind: "warm",
    note: "Bright Canadian Korean idol meets bright reaper fan. Two lowercase i registers, two K pop reference frames overlapping. The risk is Imani going self conscious about her bright wrapper; the win is the cleanest sit either has had.",
  },
  {
    a: "sienna",
    b: "alex",
    kind: "surprise",
    note: "Loud start sincere meets pick me sincere. Both say for sure too many times, both pick from a short list. Surprise warm with two patio orders and no workshopping.",
  },
  {
    a: "sienna",
    b: "naia",
    kind: "warm",
    note: "Generous compliments without keeping count, on both sides. Naia takes literally me at face value and returns the energy unscored.",
  },
  {
    a: "sienna",
    b: "mei",
    kind: "warm",
    note: "Peer recognition between working crafts. Different vocabularies (choreography vs gear), identical end of sentence expectation.",
  },
  {
    a: "sienna",
    b: "cassie",
    kind: "volatile",
    note: "Mirror, not match. Two camera trained dimensions, opposite postures. Cassie sees the cage and runs; Sienna does not know there is one to be off.",
  },
  {
    a: "sienna",
    b: "gabriel",
    kind: "friction",
    note: "Dry deadpan refuses to volley fan service energy. He goes three words; she fills the silence with a compliment that lands wrong.",
  },
  {
    a: "sienna",
    b: "sera",
    kind: "friction",
    note: "Clipped audit register meets for sure for sure. Sera offers Standard Terms on message two; Sienna says yes and panics. The yes saying compounds.",
  },
  {
    a: "sienna",
    b: "cha",
    kind: "friction",
    note: "Shared profession, mismatched register. Combat strength filter clocks her as combat tier, but the pick me wrapper reads as wrong category.",
  },
  {
    a: "sienna",
    b: "brady",
    kind: "friction",
    note: "Bit collision in the pick me direction. He runs the editor's note shtick; she answers sincerely with a thank you and apologizes for being early. He visibly loses the footing.",
  },
  {
    a: "sienna",
    b: "mira",
    kind: "friction",
    note: "Mira clocks an artist with a tour and a unit and starts pitching a brand partnership over the second martini. Sienna says yes, realizes mid entree she has been pitched.",
  },
  {
    a: "sienna",
    b: "kade",
    kind: "hard-stop",
    note: "Filming the table fires her label clause on the first phone reach. The brightness breaks for the first time in months and the apology cycle starts.",
  },
  {
    a: "sienna",
    b: "mr-whiskers",
    kind: "friction",
    note: "He hates baby talk and informal register; she calls the server bud and apologizes to the host for being early. Cold mutual courtesy at best, formal collapse at worst.",
  },

  // Junie matrix
  {
    a: "junie",
    b: "marcus",
    kind: "clean",
    note: "Mundane domesticity meets vet sincerity. Marcus has a dog and a parking lot routine; Junie has a hamster story and a stone guardian who fits on the floor. Probably her cleanest closer in the roster.",
  },
  {
    a: "junie",
    b: "nawal",
    kind: "warm",
    note: "Civil-service silence meets baseline ventriloquy. Otis being still and unspeaking does not bother Nawal at all; the ventriloquy lands as plain talk.",
  },
  {
    a: "junie",
    b: "naia",
    kind: "warm",
    note: "Face-value compliments and face-value disclosures, on both sides. Naia greets Otis by name and asks how old he is; Junie answers fifteen and is corrected only by her own count of him.",
  },
  {
    a: "junie",
    b: "aldric",
    kind: "warm",
    note: "Sworn knight reads Otis as a guardian-familiar of the household. He recognizes the pattern from his order, calls Otis the watch, and treats his presence as honor done to the table.",
  },
  {
    a: "junie",
    b: "reaver",
    kind: "friction",
    note: "He prices Otis as Equity inside the first message and asks whether the bonded household guardian transfers with the Patron arrangement. Junie has no Liquidity and Otis is not on a manifest.",
  },
  {
    a: "junie",
    b: "kade",
    kind: "hard-stop",
    note: "He reaches for the phone within five minutes to film Otis. The ring-light dealbreaker fires; the constant ventriloquy reads to him as a bit he wants to capture.",
  },
  {
    a: "junie",
    b: "mr-whiskers",
    kind: "hard-stop",
    note: "He refuses informal register and baby talk; her lowercase i, vet voice, and Otis-says-hi cadence fire both lines inside the first message. He also reads Otis at the table as a chair situation that is not civilized.",
  },
  {
    a: "junie",
    b: "cha",
    kind: "friction",
    note: "Combat-strength filter clocks Otis as adjacent to the shades he hunts. Cha lands two-word replies and does not soften toward the eye-count tells.",
  },

  // Anubis matrix
  {
    a: "anubis",
    b: "venus",
    kind: "volatile",
    note: "Two vain deities at the same maitre d's bow. Venus counts compliments; Anubis flexes the office. Whoever the bow goes to first sets the tone. Volatile-warm if either yields the first name without protest; otherwise the loudest exit in the roster.",
  },
  {
    a: "anubis",
    b: "mr-whiskers",
    kind: "surprise",
    note: "Business-class mutual courtesy in a new shape. Both refuse to address the obvious species question, both treat their work as a senior office. Surprise warm. The risk is one of them naming what the other actually is.",
  },
  {
    a: "anubis",
    b: "sera",
    kind: "volatile",
    note: "The Forty-Two judges meet Standard Terms. He chairs a review board on the weighing of hearts; she audits cohabitation contracts. Either fluent professional recognition or a contractual feud.",
  },
  {
    a: "anubis",
    b: "opal",
    kind: "hard-stop",
    note: "She clocks judge of souls before the appetizer and her binder fires on the second course. He drops the Hall of Two Truths casually, names the weighing as the day job, and the prophecy-averse line gets crossed without him noticing.",
  },
  {
    a: "anubis",
    b: "anansi",
    kind: "volatile",
    note: "Two performer-gods at the same table. Anansi tells a small lie aloud; Anubis names it out of professional courtesy and the trick has nowhere to land. Volatile-warm if both crack at the same time.",
  },
  {
    a: "anubis",
    b: "cassie",
    kind: "volatile",
    note: "Brand asset meets executive brand. He pitches the Hall of Two Truths like a season pilot; she clocks the brand voice on the second sentence. Either she softens and lets the pitch breathe, or the release-form energy fires and the dinner ends in mutual professional courtesy.",
  },
  {
    a: "anubis",
    b: "sana",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Sincerity-seekers read the divine lounge bravado as exhausting.",
  },
  {
    a: "anubis",
    b: "marcus",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Sincerity tribe disengages from divine performance.",
  },
  {
    a: "anubis",
    b: "toby",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Anubis reads ordinary conversation requests as a downgrade.",
  },
  {
    a: "anubis",
    b: "jenna",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Jenna disengages from divine performance.",
  },
  {
    a: "anubis",
    b: "mei",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Mei is hyperfocused on craft, not divine office bravado.",
  },
  {
    a: "anubis",
    b: "ryan",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Bro register disengages from divine performance.",
  },
  {
    a: "anubis",
    b: "junie",
    kind: "hard-stop",
    note: "Worst-date-ever territory. Vet sincerity disengages from divine performance.",
  },

  // Coverage audit additions
  {
    a: "meridian",
    b: "tasha",
    kind: "surprise",
    note: "Clearance brief meets market brief. Both value a confirmed plan, a clean exit ramp, and a partner who does not negotiate the venue twice. The warmth is procedural before it is romantic.",
  },
  {
    a: "meridian",
    b: "sera",
    kind: "warm",
    note: "Operational discretion meets Standard Terms. Meridian clocks the exit plan, Sera clocks the redaction discipline, and neither mistakes withholding for mystery bait.",
  },
  {
    a: "meridian",
    b: "calvin",
    kind: "clean",
    note: "Two privacy systems with different stories. He denies the strange thing; she redacts it. If neither asks for the file, the table stays calm.",
  },
  {
    a: "meridian",
    b: "maeve",
    kind: "clean",
    note: "Redacted heart meets the woman who lets questions remain unasked. Maeve does not chase the clearance file. Meridian does not audit the unsent sentence.",
  },
  {
    a: "meridian",
    b: "mr-whiskers",
    kind: "friction",
    note: "Formal lockup. Both arrive armored, clipped, and correct. Neither offers the first softening move, so the date can become two polite security checkpoints sharing an appetizer.",
  },
  {
    a: "meridian",
    b: "kade",
    kind: "hard-stop",
    note: "Phone on table, camera instinct, soft-launch vocabulary. Meridian's recording line trips before the second course and the package exits under standard protocol.",
  },
  {
    a: "meridian",
    b: "alex",
    kind: "friction",
    note: "Alex opens loud and runs live commentary. Meridian reads the volume, score checks, and table scan as an unstable room. He thinks he is being transparent; she has already moved seats twice.",
  },
  {
    a: "meridian",
    b: "epsy",
    kind: "friction",
    note: "Face-up phone company meets a no-recording field office. Epsy drops the substrate thing at small-talk volume; Meridian starts redacting the air.",
  },
  {
    a: "meridian",
    b: "mira",
    kind: "volatile",
    note: "Calendar competence and car-service polish land first. Then Mira names Sage, asks one clearance-shaped question, and Meridian treats the whole table as a breach review.",
  },
  {
    a: "alex",
    b: "ryan",
    kind: "warm",
    note: "Two loud sincere men who think the app is normal. Sports talk burns off into patio logistics, and neither treats the early read as cruelty.",
  },
  {
    a: "alex",
    b: "noah",
    kind: "warm",
    note: "Hot takes meet seven hobbies and one exhausted resident. Alex defends a sports position; Noah counters with a niche thing and asks three real follow-ups.",
  },
  {
    a: "alex",
    b: "tasha",
    kind: "volatile",
    note: "Competitive confidence on both sides. He calls a read at the half, she marks the position to market, and the room either sparks or becomes a panel show with appetizers.",
  },
  {
    a: "alex",
    b: "gabriel",
    kind: "surprise",
    note: "Loud take machine meets three-word deadpan. Gabriel lets one debate run, lands one pun, and Alex treats the walk-back as the rare correct replay review.",
  },
  {
    a: "alex",
    b: "venus",
    kind: "friction",
    note: "Both want the room to notice the right thing. Alex watches the score and argues the take; Venus counts compliments and files the sports detour under insufficient worship.",
  },
  {
    a: "alex",
    b: "kade",
    kind: "friction",
    note: "Attention rivalry with two cameras implied. Alex wants a debate, Kade wants a clip, and neither wants the other to own the room.",
  },
  {
    a: "alex",
    b: "mr-whiskers",
    kind: "friction",
    note: "Loud early read meets formal service standards. Alex calls the quarter too soon; Mr. Whiskers treats the sports bar register as a failure of civilization.",
  },
  {
    a: "tasha",
    b: "mira",
    kind: "volatile",
    note: "Founder pitch meets trading pitch. They admire the confirmed calendar and immediately start pricing each other's language. Warm if they laugh first, cold if either says asset class twice.",
  },
  {
    a: "tasha",
    b: "noah",
    kind: "surprise",
    note: "Market close meets post-call brunch. Tasha respects a held time; Noah respects a person who treats the shift as a fact and not a character trial.",
  },
  {
    a: "tasha",
    b: "gabriel",
    kind: "surprise",
    note: "Two clipped city registers with no patience for wasted motion. He puns once, she compresses the thesis, and both are relieved by the lack of brunch energy.",
  },
  {
    a: "tasha",
    b: "venus",
    kind: "friction",
    note: "Competitive collision. Tasha wants the trade named cleanly; Venus wants the bow counted correctly. Spark high, trust low, exit statements prepared.",
  },
  {
    a: "tasha",
    b: "mr-whiskers",
    kind: "friction",
    note: "Two professionals grading the room. She sizes the position, he grades the service, and neither appreciates being treated as the counterparty with less authority.",
  },
  {
    a: "tasha",
    b: "brady",
    kind: "friction",
    note: "Negotiation pitch meets editor's-note shtick. Tasha asks for the one-line thesis; Brady gives a bit about the thesis and the bid collapses.",
  },
  {
    a: "tasha",
    b: "maeve",
    kind: "friction",
    note: "Tasha turns feelings into a position. Maeve lets the unsaid stay unsaid. The first time Capital becomes a dinner topic, the meal stops being the meal.",
  },
  {
    a: "gabriel",
    b: "mei",
    kind: "clean",
    note: "The cleanest dry-deadpan landing. Mei treats the pun as craft, Gabriel lets the gear talk run, and nobody explains the joke after the joke.",
  },
  {
    a: "gabriel",
    b: "sera",
    kind: "surprise",
    note: "Dry deadpan meets audit protocol. If either drops the shield for one sentence, the efficiency becomes warmth instead of sterile fluency.",
  },
  {
    a: "gabriel",
    b: "derek",
    kind: "clean",
    note: "Pun tolerance and quiet starts. Derek lets the walk-back land. Gabriel lets the first ten minutes stay small. Both pretend that counts as casual.",
  },
  {
    a: "gabriel",
    b: "maeve",
    kind: "surprise",
    note: "Three-word question meets a woman who does not return the harder one. The silence is allowed to sit, and Gabriel discovers he does not have to undercut it.",
  },
  {
    a: "gabriel",
    b: "kade",
    kind: "friction",
    note: "Soft-launch noise meets three-word refusal. Gabriel will not be b-roll, and Kade reads the deadpan as hostile to the room he is trying to capture.",
  },
  {
    a: "gabriel",
    b: "mira",
    kind: "friction",
    note: "Founder pitch meets deadpan. Mira opens with intentionality and Carnegie; Gabriel answers in three words and does not download Sage.",
  },
  {
    a: "gabriel",
    b: "brady",
    kind: "friction",
    note: "Bit collision, colder register. Brady tries to narrate the date from outside it; Gabriel clocks the device and refuses the volley.",
  },
  {
    a: "gabriel",
    b: "naia",
    kind: "friction",
    note: "Naia takes the charmander line at face value, which leaves the irony stranded. Gabriel cannot decide whether the failed bit was failure or a better answer.",
  },
  {
    a: "gabriel",
    b: "aldric",
    kind: "friction",
    note: "Deadpan wordplay meets knightly sincerity. Aldric reads the walk-back as discourtesy, and Gabriel cannot make the joke smaller without removing himself from it.",
  },
  {
    a: "gideon",
    b: "sana",
    kind: "warm",
    note: "Tender sincerity and slow questions. Sana says his name without turning the ghost into content, and Gideon lets the lamp mean something small.",
  },
  {
    a: "gideon",
    b: "marcus",
    kind: "clean",
    note: "Mundane care meets a haunted room. Marcus keeps the reservation, asks the history once, and does not make Gideon perform the haunting.",
  },
  {
    a: "gideon",
    b: "idris",
    kind: "clean",
    note: "Remembered name meets retired title. Both want the past handled once and then set down gently enough that dinner can continue.",
  },
  {
    a: "gideon",
    b: "nawal",
    kind: "clean",
    note: "Low intimacy grief pair. She does not ask him to perform recovery, and he does not ask her to explain the office she no longer holds.",
  },
  {
    a: "gideon",
    b: "maeve",
    kind: "volatile",
    note: "He wants to be remembered; she feeds on the almost and will not chase the harder thing. Beautiful if the restraint holds, devastating if he asks her to name the hunger.",
  },
  {
    a: "gideon",
    b: "kade",
    kind: "hard-stop",
    note: "Filming the haunting is on Gideon's list before the date begins. Kade sees a lamp moment; Gideon sees a special effect being booked without consent.",
  },
  {
    a: "gideon",
    b: "anubis",
    kind: "hard-stop",
    note: "Dead man meets judge of souls. Anubis treats the office as ordinary authority, and Gideon did not come to dinner for a remote hearing.",
  },
  {
    a: "gideon",
    b: "reaver",
    kind: "friction",
    note: "Recovery contract meets a man who has already lost the body. Reaver prices usefulness; Gideon hears a new version of being made into a room feature.",
  },
  {
    a: "gideon",
    b: "brady",
    kind: "friction",
    note: "Editor voice meets a ghost who asked not to be called unfinished business. Brady reaches for the wrong joke and the lamp takes it personally.",
  },
  {
    a: "eleanor",
    b: "mr-whiskers",
    kind: "friction",
    note: "Formal lockup. Both preserve dignity by refusing the ordinary softening move. The courtesy is flawless and airless.",
  },
  {
    a: "eleanor",
    b: "kade",
    kind: "friction",
    note: "Literal truth meets content framing. Kade soft-launches the room, Eleanor answers exactly what he implied, and the bit loses all deniability.",
  },
  {
    a: "eleanor",
    b: "mira",
    kind: "friction",
    note: "Fae bargain meets founder vulnerability beat. Eleanor cannot lie, and Mira's manufactured openness gets audited faster than Sage can call it growth.",
  },
  {
    a: "eleanor",
    b: "alex",
    kind: "friction",
    note: "Literal courtly truth meets live sports absolutism. Alex changes sides for the argument; Eleanor records that as an oath with a problem.",
  },
  {
    a: "jenna",
    b: "derek",
    kind: "warm",
    note: "Ordinary app expectations, low pressure, and one quiet start. Jenna lets the first ten minutes warm without turning it into a referendum.",
  },
  {
    a: "jenna",
    b: "noah",
    kind: "warm",
    note: "Normal-date expectations meet a resident who wants one hobby traded cleanly. She treats the shift as logistics, not as a flaw to repair.",
  },
  {
    a: "jenna",
    b: "sera",
    kind: "friction",
    note: "Jenna thinks Cupid is a normal app. Sera offers Standard Terms and week-three review. The sincere pace reads the protocol as evasion.",
  },
  {
    a: "jenna",
    b: "kade",
    kind: "friction",
    note: "Normal app sincerity meets content-table habits. Jenna did not sign up to be a soft-launch prop, and Kade cannot keep the room unfilmed enough.",
  },
  {
    a: "mr-whiskers",
    b: "maeve",
    kind: "clean",
    note: "Formal table discipline with no baby talk and no forced disclosure. Maeve lets the office remain unnamed; Mr. Whiskers lets the meal proceed correctly.",
  },
  {
    a: "mr-whiskers",
    b: "sera",
    kind: "surprise",
    note: "Two clipped operators with a shared respect for schedule, terms, and not saying the obvious species problem out loud.",
  },
  {
    a: "mr-whiskers",
    b: "venus",
    kind: "friction",
    note: "Competitive service economy. Venus counts compliments; Mr. Whiskers counts standards, and neither count flatters the other fast enough.",
  },
  {
    a: "opal",
    b: "derek",
    kind: "surprise",
    note: "Low-pressure ordinary with no prophecy language. Derek's first ten minutes are blessedly small, and Opal's binder has nothing ceremonial to bite.",
  },
  {
    a: "opal",
    b: "noah",
    kind: "surprise",
    note: "A resident with hobbies is refreshingly non-fated. Noah asks too many follow-ups about the safe things and lets the cosmic door stay closed.",
  },
  {
    a: "opal",
    b: "vhool",
    kind: "hard-stop",
    note: "Pact talk lands exactly where her binder is thickest. Vhool is sincere, which makes the prophecy pressure worse instead of softer.",
  },
  {
    a: "opal",
    b: "wenshu",
    kind: "hard-stop",
    note: "He says fated and counterpart like they are compliments. Opal hears both as paperwork she has already escaped.",
  },
  {
    a: "opal",
    b: "epsy",
    kind: "friction",
    note: "Epsy treats cosmic catastrophe as small talk and then reaches for a social ritual to cover it. Opal can feel the binder opening by itself.",
  },
  {
    a: "vhool",
    b: "jenna",
    kind: "friction",
    note: "Jenna came for a normal app date. Vhool brings Pact language, choir loneliness, and a softness that still sounds like incorporation.",
  },
  {
    a: "vhool",
    b: "marcus",
    kind: "friction",
    note: "Marcus wants low pressure and no vows. Vhool means well and still makes the table feel like a vow waiting for a signature.",
  },
  {
    a: "vhool",
    b: "toby",
    kind: "friction",
    note: "Toby asks for a short list and exit clarity. Vhool hears a soft yes inside a nervous maybe, and the spiral starts doing compliance math.",
  },
  {
    a: "vhool",
    b: "maeve",
    kind: "friction",
    note: "Pact loneliness meets the woman who will not chase the harder question. Vhool reaches for kindred language; Maeve leaves the almost on the plate.",
  },
  {
    a: "cassie",
    b: "venus",
    kind: "volatile",
    note: "Glamour cluster mirror. Venus counts admiration openly; Cassie knows what a camera-trained room costs and tries not to run from the count.",
  },
  {
    a: "cassie",
    b: "kade",
    kind: "hard-stop",
    note: "Release-form energy with a ring light attached. Cassie's brand cage recognizes the content ask before Kade finishes promising it is tiny.",
  },
  {
    a: "cassie",
    b: "mira",
    kind: "friction",
    note: "Mira sees a brand asset with reach. Cassie hears the pitch before it is called a partnership and starts looking for the exit clause.",
  },
  {
    a: "decimus",
    b: "anubis",
    kind: "friction",
    note: "Retired soldier meets divine office bravado. Decimus respects offices that earn the room; Anubis brings one that expects the room to bow first.",
  },
  {
    a: "decimus",
    b: "kade",
    kind: "friction",
    note: "Legion dignity meets pickup-shot logistics. Decimus does not understand why the first course needs coverage, and Kade cannot stop narrating the angle.",
  },
  {
    a: "decimus",
    b: "venus",
    kind: "friction",
    note: "Republican austerity meets divine compliment accounting. Decimus offers courtesy without worship, which Venus does not file as payment.",
  },
  {
    a: "aldric",
    b: "mira",
    kind: "friction",
    note: "Honor meets founder pitch. Mira translates conviction into leadership potential, and Aldric hears a recruitment deck where an oath should be.",
  },
  {
    a: "aldric",
    b: "idris",
    kind: "volatile",
    note: "Knightly courtesy meets retired commander who does not want a title. If Aldric accepts the correction once, it warms. If he says sir twice, it closes.",
  },
  {
    a: "aldric",
    b: "kade",
    kind: "friction",
    note: "Knightly sincerity meets soft-launch energy. Kade asks for one tiny b-roll moment, and Aldric treats the request like discourtesy with lighting.",
  },
  {
    a: "calvin",
    b: "maeve",
    kind: "clean",
    note: "Privacy-sensitive cryptid meets privacy-native silence. Maeve does not ask what he is, and Calvin almost forgets to deny it.",
  },
  {
    a: "calvin",
    b: "epsy",
    kind: "friction",
    note: "Calvin hides the impossible thing. Epsy introduces hers at full brightness, body panels included, and likes the phone company.",
  },
  {
    a: "marcus",
    b: "kade",
    kind: "friction",
    note: "Sincerity-seeker meets filming instinct. Marcus can forgive nerves, but not being turned into material before the bread arrives.",
  },
  {
    a: "derek",
    b: "marcus",
    kind: "clean",
    note: "Quiet ordinary men with practical work and low-pressure timing. Derek gets his first ten minutes, Marcus gets a normal answer, and nobody performs range.",
  },
  {
    a: "derek",
    b: "sana",
    kind: "warm",
    note: "Sana lets the quiet start be quiet and takes the dad pun as the bid it is. Derek notices without making a speech about noticing.",
  },
  {
    a: "derek",
    b: "brady",
    kind: "friction",
    note: "Flat dad pun meets editor's-note bit. Brady tries to annotate the joke, and Derek treats that as explaining the pun after it landed.",
  },
  {
    a: "derek",
    b: "kade",
    kind: "hard-stop",
    note: "Quiet first ten minutes meet a camera on the table. Derek does not want the date filmed, graded, or turned into the before part of a vlog.",
  },
  {
    a: "derek",
    b: "mira",
    kind: "friction",
    note: "Federal claims calm meets founder energy. Mira tries to find the hidden ambition; Derek hears another person calling the boring job a problem to solve.",
  },
  {
    a: "derek",
    b: "anubis",
    kind: "hard-stop",
    note: "Quiet federal baseline meets divine lounge authority. Anubis makes the room a review board before Derek has warmed the engine.",
  },
  {
    a: "noah",
    b: "mei",
    kind: "warm",
    note: "Rapid hobby enthusiasm on both sides. Noah asks too many follow-ups about the set; Mei answers at gear speed and neither runs out of thread.",
  },
  {
    a: "noah",
    b: "epsy",
    kind: "warm",
    note: "Seven hobbies meets shrimp, clubbing, and body calibration. Noah treats the niche list as a hobby tray instead of a diagnosis.",
  },
  {
    a: "noah",
    b: "sienna",
    kind: "warm",
    note: "Earnest enthusiast meets bright working artist. She can name a whole scene; he can ask too many follow-ups and mean each one.",
  },
  {
    a: "noah",
    b: "mira",
    kind: "friction",
    note: "Resident fatigue meets founder optimization. Mira wants intentionality by EOD; Noah hears sleep debt being converted into an OKR.",
  },
  {
    a: "noah",
    b: "kade",
    kind: "friction",
    note: "Niche hobby enthusiasm becomes content too fast. Noah brought a topic to trade, not a pickup shot with a caption about residents.",
  },
  {
    a: "noah",
    b: "anubis",
    kind: "hard-stop",
    note: "Exhausted resident meets divine performance review. Noah needed the shift treated as a fact; Anubis makes the whole room an office.",
  },
  {
    a: "noah",
    b: "brady",
    kind: "friction",
    note: "Noah asks a real follow-up about the bit, which is exactly where Brady does not want the room to go. The shtick gets paged and fails to return.",
  },
  {
    a: "epsy",
    b: "mei",
    kind: "warm",
    note: "Epsy is already front row for Mei's set in her own profile. Mei reads the body calibration as craft-adjacent, and Epsy treats the music as a stable law.",
  },
  {
    a: "epsy",
    b: "naia",
    kind: "warm",
    note: "Face-value weirdness meets face-value royalty. Naia does not ask which species the shrimp was, and Epsy does not have to pick between the bit and the underneath.",
  },
  {
    a: "epsy",
    b: "imani",
    kind: "surprise",
    note: "Bright reaper meets bright synthetic survivor. Imani can hear the death-adjacent part without making it homework, and Epsy gets to name it once and move on.",
  },
  {
    a: "epsy",
    b: "kade",
    kind: "volatile",
    note: "Two attention systems and one camera problem. Kade sees the body as perfect content; Epsy might enjoy the bit until he calls her a prototype by accident.",
  },
  {
    a: "kade",
    b: "venus",
    kind: "volatile",
    note: "Attention-seeker meets compliment accountant. Venus likes being framed when she controls the frame; Kade likes any frame that posts. The first good angle could warm or end it.",
  },
  {
    a: "kade",
    b: "mira",
    kind: "volatile",
    note: "Creator funnel meets founder funnel. Mira sees distribution, Kade sees status, and both can briefly mistake mutual extraction for chemistry.",
  },
  {
    a: "mira",
    b: "mr-whiskers",
    kind: "surprise",
    note: "Professional register in two costumes. Mira respects a senior office when it comes with standards; Mr. Whiskers respects a confirmed calendar when she stops saying funnel.",
  },
  {
    a: "mira",
    b: "sera",
    kind: "volatile",
    note: "Founder OKRs meet Standard Terms. Both admire a clean contract and both believe they should own the template.",
  },
  {
    a: "epsy",
    b: "maeve",
    kind: "friction",
    note: "Epsy names the civilization at small-talk volume and then over-corrects. Maeve prefers the question almost asked, not the catastrophe placed cheerfully in the center of the table.",
  },
  {
    a: "epsy",
    b: "anubis",
    kind: "friction",
    note: "She ended a civilization and is trying to be normal about shrimp. He chairs a judgment office and will not leave the obvious category alone.",
  },
  {
    a: "idris",
    b: "decimus",
    kind: "clean",
    note: "Two retired commanders who understand that the title can be the wound. Decimus offers soldierly recognition without asking Idris to lead.",
  },
  {
    a: "idris",
    b: "cha",
    kind: "clean",
    note: "Combat-tier quiet, post-command fatigue. Cha respects strength without requiring a speech, and Idris does not ask him to translate the silence.",
  },
  {
    a: "idris",
    b: "nawal",
    kind: "clean",
    note: "Retired office meets retired command. Both declined the role after it stopped being survivable, and neither needs the other to perform recovery.",
  },
  {
    a: "idris",
    b: "sana",
    kind: "warm",
    note: "Sana can ask once about the war and let the answer hold. Idris gets his first name back at normal volume.",
  },
  {
    a: "idris",
    b: "reaver",
    kind: "hard-stop",
    note: "Retired liberator meets active recruiter. Reaver's Manifest sounds like the exact machinery Idris left a world to stop hearing.",
  },
  {
    a: "idris",
    b: "kade",
    kind: "hard-stop",
    note: "Photographing the bow, scars, or pendant is already on Idris's list. Kade reaches for the visual before he understands what he is filming.",
  },
  {
    a: "idris",
    b: "anubis",
    kind: "friction",
    note: "Retired leader avoiding titles meets a god who chairs judgment like a standing meeting. Idris does not need another room where his past is reviewed.",
  },
  {
    a: "idris",
    b: "mira",
    kind: "friction",
    note: "Mira hears former leader and starts organizing the potential. Idris came to dinner to be no one's project, cause, or board seat.",
  },
  {
    a: "maeve",
    b: "nawal",
    kind: "clean",
    note: "Two women who let a closed office remain closed. The silence is not tension, the meal is not a debrief, and nobody asks for a harder thing.",
  },
  {
    a: "maeve",
    b: "kade",
    kind: "hard-stop",
    note: "Phone on table, filmed atmosphere, and the question pushed one sentence too far. Maeve pays for her own and leaves the meal to him.",
  },
  {
    a: "maeve",
    b: "mira",
    kind: "hard-stop",
    note: "Mira asks what Maeve does and tries to turn the answer into growth. Maeve told the table the question was not the meal.",
  },
  {
    a: "maeve",
    b: "anubis",
    kind: "friction",
    note: "Anubis cannot resist naming the office and the weighing. Maeve does not absolve, confess, or feed the question once it arrives with a title.",
  },
  {
    a: "wenshu",
    b: "naia",
    kind: "surprise",
    note: "Lyrical ceremony meets face-value princess manners. Naia accepts the form as local color and does not punish him for ornament until he asks the form to choose for her.",
  },
  {
    a: "sana",
    b: "kade",
    kind: "friction",
    note: "Sincerity-seeker meets content reflex. Sana reads the filming as evasion before Kade can explain that the evasion is also the business model.",
  },
  {
    a: "sera",
    b: "toby",
    kind: "friction",
    note: "Toby asks for one short list and a clean exit. Sera answers with Standard Terms and a cohabitation review cadence that makes his apology loop stand up.",
  },
  {
    a: "toby",
    b: "kade",
    kind: "friction",
    note: "Anxious spiral compound with a camera. Kade tries to make the awkwardness usable, and Toby hears the room becoming evidence against him.",
  },
  {
    a: "brady",
    b: "kade",
    kind: "volatile",
    note: "Different vintages, same dishonesty. Each can feel the other doing it. If one drops the cover first it warms; if neither does, the bit eats dinner alone.",
  },

  // John matrix
  {
    a: "john",
    b: "decimus",
    kind: "warm",
    note: "Two Republic operators recognizing each other. Decimus respects offices that earn the room; John runs a State of the Farm with the same gravity Decimus carries the Tenth Legion. Different Republics, same vocabulary of civic duty. Neither lowers the dignity of their post.",
  },
  {
    a: "john",
    b: "eleanor",
    kind: "warm",
    note: "Committee cadence meets contractual fae. Eleanor cannot lie; John declares Commitments by the second course. Both treat dignity as a binding instrument and would rather skip dessert than negotiate the wording. Cold formal allies.",
  },
  {
    a: "john",
    b: "wenshu",
    kind: "warm",
    note: "Dao-talk meets Plan-talk. Both arrive in the suit and the customs, both treat their realm's ceremonial vocabulary as ordinary table conversation. Risk: John hears Romance Dao as fate-coded and tightens. Wenshu does not actually mean fated the way Opal hears it; John may need a course to clock that.",
  },
  {
    a: "john",
    b: "aldric",
    kind: "warm",
    note: "Knight meets Manager. Two office-bearers from different realms carrying the charge the same way. Aldric addresses him as Manager; John registers the courtesy and answers in kind. Different scriptures, identical conviction that the office is the answer.",
  },
  {
    a: "john",
    b: "mr-whiskers",
    kind: "surprise",
    note: "Business-class mutual courtesy in a new shape. Both refuse to address the obvious species question, both confirm Thursday in writing. The pork in front of one of them and the chair the other will not name go unnoticed by design. Whichever names the other first ends the courtesy.",
  },
  {
    a: "john",
    b: "reaver",
    kind: "acquisition",
    note: "Plan talk meets Manifest talk. Two structured recruiters at the same table, both refusing to lower the ask. John interviews for comrade-spouse with declared Commitments; Reaver opens with Liquidity. Match-fit fires pair:mutual_acquisition. Volatile-warm if neither asks whose contradictions are bigger.",
  },
  {
    a: "john",
    b: "vhool",
    kind: "acquisition",
    note: "Pact talk meets Plan talk. Both sincere about a recruitment cadence they would not call recruitment. Vhool apologizes after every implied threat; John reads the committee minutes back as a compliment. The mirror is uncomfortable for both. Volatile-warm if both stay deadpan.",
  },
  {
    a: "john",
    b: "cthala",
    kind: "acquisition",
    note: "Plan talk meets Consort talk. Two acquisitive operators from opposite tones: his bureaucratic-egalitarian, hers calm and chosen-form. Neither apologizes. Match-fit reads pair:mutual_acquisition. The friction is two recruiters openly at the same dinner.",
  },
  {
    a: "john",
    b: "naia",
    kind: "surprise",
    note: "Face-value princess takes the comrade-spouse interview at face value. She asks how the household allowance works in the Republic, listens to the answer, and offers no counter. John does not know what to do with a counterpart who registers the proposal as ordinary courtesy. Possibly his cleanest sit, possibly the date that closes when the toast goes unscored.",
  },
  {
    a: "john",
    b: "maeve",
    kind: "friction",
    note: "Committee cadence asks the harder thing as a deliverable. Maeve does not return harder questions and asks once that the trade stay closed. John registers the silence as missing data; Maeve registers the agenda as the question she will not answer. The meal stops being the meal.",
  },
  {
    a: "john",
    b: "mira",
    kind: "friction",
    note: "Committee functionary meets founder pitch. Mira files an amendment during the entree about how the Farm could ten-x with a brand layer. John's dealbreaker on amendments-during-entree fires by message three. Both close the file calmly, both convinced the other lacks intentionality.",
  },
  {
    a: "john",
    b: "opal",
    kind: "hard-stop",
    note: "Comrade-spouse interview with declared Commitments and a toast confirmed before the entree hits Opal's binder on the first paragraph. State of the Farm reads as fate language, the structured Plan reads as paperwork she has already escaped, and the deadpan does not soften any of it.",
  },
  {
    a: "john",
    b: "sana",
    kind: "hard-stop",
    note: "Sincerity tribe disengagement. Sana wants ten quiet minutes; John arrives with a printed agenda and the toast confirmed. The recruiter cadence does not register as sincerity to her, no matter how earnest the delivery.",
  },

  // Cassia anchors
  {
    a: "cassia",
    b: "cha",
    kind: "warm",
    note: "Two combat-class displaced soldiers from different shooter dimensions, both standing in wars that ended without them. Cha never asks. Cassia is grateful for the never-asking. They share the silence and neither files it as withholding.",
  },
  {
    a: "cassia",
    b: "marcus",
    kind: "warm",
    note: "Sincerity tribe holding space. Marcus hears the helmet rules once and does not return to them. Cassia gets to set the disclosure down. The first date she does not have to apologize for the armor.",
  },
  {
    a: "cassia",
    b: "idris",
    kind: "warm",
    note: "Retired commander recognizes a soldier still at attention for a battle that is no longer happening. Idris does not flex the title. Cassia does not have to perform rank. The grief lands ambient and is not picked up.",
  },
  {
    a: "cassia",
    b: "calvin",
    kind: "warm",
    note: "Two refusals to be inspected. Calvin denies the strange thing about himself; Cassia is convinced she is in stealth. Neither reaches. The mutual cover is the date.",
  },
  {
    a: "cassia",
    b: "toby",
    kind: "volatile",
    note: "Anxious-spiral compound. Toby's overthinking meets Cassia's overstudy and both spiral wider. Either an intimate match where both feel finally seen, or a runaway loop where neither lands a sentence.",
  },
  {
    a: "cassia",
    b: "kade",
    kind: "friction",
    note: "Recorder versus filming-the-visor dealbreaker. Kade arrives planning to soft-launch a content angle on the helmet; Cassia reads the camera angle as the moment she has been preparing for. She offers him the bribe drawer and exfiltrates.",
  },
  {
    a: "cassia",
    b: "brady",
    kind: "friction",
    note: "Bit cracks against earnest oversharing. Brady performs warmth from a vintage; Cassia has rehearsed warmth from a forum thread. They recognize each other doing it and the date hollows out in real time.",
  },
  {
    a: "cassia",
    b: "mira",
    kind: "friction",
    note: "Founder pitch hits privacy-sensitive at the cocktail. Mira asks how Cassia is monetizing the construct angle and files an amendment about brand layer by the second course. Cassia hears coordinator and starts pricing the energy sword.",
  },
  {
    a: "cassia",
    b: "anansi",
    kind: "friction",
    note: "Trickster curiosity treats the helmet as a riddle. Anansi will pose the seam question three different ways, each one warm and obliging. Cassia is not a riddle. She is afraid of being one.",
  },
];
